// <copyright file="ApiV1DeploymentsFindingsResponseFindings.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace SemgrepWebApp.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<ApiV1DeploymentsFindingsResponseFindings>),
        new[] {
            typeof(SastFindingCase),
            typeof(ScaFindingCase),
            typeof(AiPoweredScanFindingCase)
        },
        true
    )]
    public abstract class ApiV1DeploymentsFindingsResponseFindings
    {
        /// <summary>
        /// This is Sast Finding case.
        /// </summary>
        /// <returns>
        /// The ApiV1DeploymentsFindingsResponseFindings instance, wrapping the provided SastFinding value.
        /// </returns>
        public static ApiV1DeploymentsFindingsResponseFindings FromSastFinding(SastFinding sastFinding)
        {
            return new SastFindingCase().Set(sastFinding);
        }

        /// <summary>
        /// This is Sca Finding case.
        /// </summary>
        /// <returns>
        /// The ApiV1DeploymentsFindingsResponseFindings instance, wrapping the provided ScaFinding value.
        /// </returns>
        public static ApiV1DeploymentsFindingsResponseFindings FromScaFinding(ScaFinding scaFinding)
        {
            return new ScaFindingCase().Set(scaFinding);
        }

        /// <summary>
        /// This is AI-Powered Scan Finding case.
        /// </summary>
        /// <returns>
        /// The ApiV1DeploymentsFindingsResponseFindings instance, wrapping the provided AiPoweredScanFinding value.
        /// </returns>
        public static ApiV1DeploymentsFindingsResponseFindings FromAIPoweredScanFinding(AiPoweredScanFinding aiPoweredScanFinding)
        {
            return new AiPoweredScanFindingCase().Set(aiPoweredScanFinding);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<SastFinding, T> sastFinding,
            Func<ScaFinding, T> scaFinding,
            Func<AiPoweredScanFinding, T> aiPoweredScanFinding);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<SastFinding, T> sastFinding = null,
            Func<ScaFinding, T> scaFinding = null,
            Func<AiPoweredScanFinding, T> aiPoweredScanFinding = null) =>
                Match(sastFinding, scaFinding, aiPoweredScanFinding);

        [JsonConverter(typeof(UnionTypeCaseConverter<SastFindingCase, SastFinding>))]
        private sealed class SastFindingCase : ApiV1DeploymentsFindingsResponseFindings, ICaseValue<SastFindingCase, SastFinding>
        {
            public SastFinding Value;

            public override T Match<T>(
                Func<SastFinding, T> sastFinding,
                Func<ScaFinding, T> scaFinding,
                Func<AiPoweredScanFinding, T> aiPoweredScanFinding) =>
                   sastFinding != null ? sastFinding(Value) : default;

            public SastFindingCase Set(SastFinding value)
            {
                Value = value;
                return this;
            }

            public SastFinding Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ScaFindingCase, ScaFinding>))]
        private sealed class ScaFindingCase : ApiV1DeploymentsFindingsResponseFindings, ICaseValue<ScaFindingCase, ScaFinding>
        {
            public ScaFinding Value;

            public override T Match<T>(
                Func<SastFinding, T> sastFinding,
                Func<ScaFinding, T> scaFinding,
                Func<AiPoweredScanFinding, T> aiPoweredScanFinding) =>
                   scaFinding != null ? scaFinding(Value) : default;

            public ScaFindingCase Set(ScaFinding value)
            {
                Value = value;
                return this;
            }

            public ScaFinding Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<AiPoweredScanFindingCase, AiPoweredScanFinding>))]
        private sealed class AiPoweredScanFindingCase : ApiV1DeploymentsFindingsResponseFindings, ICaseValue<AiPoweredScanFindingCase, AiPoweredScanFinding>
        {
            public AiPoweredScanFinding Value;

            public override T Match<T>(
                Func<SastFinding, T> sastFinding,
                Func<ScaFinding, T> scaFinding,
                Func<AiPoweredScanFinding, T> aiPoweredScanFinding) =>
                   aiPoweredScanFinding != null ? aiPoweredScanFinding(Value) : default;

            public AiPoweredScanFindingCase Set(AiPoweredScanFinding value)
            {
                Value = value;
                return this;
            }

            public AiPoweredScanFinding Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}