// <copyright file="FindingsServiceApi.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using SemgrepWebApp.Standard.Http.Response;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SemgrepWebApp.Standard.Apis
{
    /// <summary>
    /// FindingsServiceApi.
    /// </summary>
    public class FindingsServiceApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FindingsServiceApi"/> class.
        /// </summary>
        internal FindingsServiceApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Request the list of code, supply chain, or AI-powered scan findings in an organization, paginated in pages of 100 entries and limited by the `since` timestamp. Findings are returned by `relevant_since` descending (see `since` in the Query Parameters list). Examples: List SAST findings with pagination, List SCA findings since timestamp, List AI-powered scan findings, List findings with filters.
        /// </summary>
        /// <param name="deploymentSlug">Required parameter: .</param>
        /// <param name="issueType">Optional parameter: Example: sast.</param>
        /// <param name="since">Optional parameter: .</param>
        /// <param name="page">Optional parameter: Example: 0.</param>
        /// <param name="dedup">Optional parameter: Example: false.</param>
        /// <param name="pageSize">Optional parameter: Example: 100.</param>
        /// <param name="repos">Optional parameter: .</param>
        /// <param name="repositoryIds">Optional parameter: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="triageReasons">Optional parameter: Example: .</param>
        /// <param name="severities">Optional parameter: Example: .</param>
        /// <param name="mRef">Optional parameter: .</param>
        /// <param name="policies">Optional parameter: .</param>
        /// <param name="rules">Optional parameter: .</param>
        /// <param name="categories">Optional parameter: .</param>
        /// <param name="confidence">Optional parameter: Example: .</param>
        /// <param name="autotriageVerdict">Optional parameter: Example: .</param>
        /// <param name="componentTags">Optional parameter: .</param>
        /// <param name="exposures">Optional parameter: Example: .</param>
        /// <param name="transitivities">Optional parameter: Example: .</param>
        /// <param name="isMalicious">Optional parameter: .</param>
        /// <param name="clickToFixPrState">Optional parameter: Example: .</param>
        /// <returns>Returns the ApiResponse of Models.ApiV1DeploymentsFindingsResponse response from the API call.</returns>
        public ApiResponse<Models.ApiV1DeploymentsFindingsResponse> FindingsServiceListFindings(
                string deploymentSlug,
                Models.IssueType2? issueType = Models.IssueType2.Sast,
                double? since = null,
                long? page = 0L,
                bool? dedup = false,
                long? pageSize = 100L,
                List<string> repos = null,
                List<long> repositoryIds = null,
                Models.Status9? status = null,
                Models.TriageReasons2? triageReasons = null,
                Models.Severities2? severities = null,
                string mRef = null,
                List<string> policies = null,
                List<string> rules = null,
                List<string> categories = null,
                Models.Confidence8? confidence = null,
                Models.AutotriageVerdict2? autotriageVerdict = null,
                List<string> componentTags = null,
                Models.Exposures2? exposures = null,
                Models.Transitivities2? transitivities = null,
                bool? isMalicious = null,
                Models.ClickToFixPrState? clickToFixPrState = null)
            => CoreHelper.RunTask(FindingsServiceListFindingsAsync(deploymentSlug, issueType, since, page, dedup, pageSize, repos, repositoryIds, status, triageReasons, severities, mRef, policies, rules, categories, confidence, autotriageVerdict, componentTags, exposures, transitivities, isMalicious, clickToFixPrState));

        /// <summary>
        /// Request the list of code, supply chain, or AI-powered scan findings in an organization, paginated in pages of 100 entries and limited by the `since` timestamp. Findings are returned by `relevant_since` descending (see `since` in the Query Parameters list). Examples: List SAST findings with pagination, List SCA findings since timestamp, List AI-powered scan findings, List findings with filters.
        /// </summary>
        /// <param name="deploymentSlug">Required parameter: .</param>
        /// <param name="issueType">Optional parameter: Example: sast.</param>
        /// <param name="since">Optional parameter: .</param>
        /// <param name="page">Optional parameter: Example: 0.</param>
        /// <param name="dedup">Optional parameter: Example: false.</param>
        /// <param name="pageSize">Optional parameter: Example: 100.</param>
        /// <param name="repos">Optional parameter: .</param>
        /// <param name="repositoryIds">Optional parameter: .</param>
        /// <param name="status">Optional parameter: Example: .</param>
        /// <param name="triageReasons">Optional parameter: Example: .</param>
        /// <param name="severities">Optional parameter: Example: .</param>
        /// <param name="mRef">Optional parameter: .</param>
        /// <param name="policies">Optional parameter: .</param>
        /// <param name="rules">Optional parameter: .</param>
        /// <param name="categories">Optional parameter: .</param>
        /// <param name="confidence">Optional parameter: Example: .</param>
        /// <param name="autotriageVerdict">Optional parameter: Example: .</param>
        /// <param name="componentTags">Optional parameter: .</param>
        /// <param name="exposures">Optional parameter: Example: .</param>
        /// <param name="transitivities">Optional parameter: Example: .</param>
        /// <param name="isMalicious">Optional parameter: .</param>
        /// <param name="clickToFixPrState">Optional parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ApiV1DeploymentsFindingsResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.ApiV1DeploymentsFindingsResponse>> FindingsServiceListFindingsAsync(
                string deploymentSlug,
                Models.IssueType2? issueType = Models.IssueType2.Sast,
                double? since = null,
                long? page = 0L,
                bool? dedup = false,
                long? pageSize = 100L,
                List<string> repos = null,
                List<long> repositoryIds = null,
                Models.Status9? status = null,
                Models.TriageReasons2? triageReasons = null,
                Models.Severities2? severities = null,
                string mRef = null,
                List<string> policies = null,
                List<string> rules = null,
                List<string> categories = null,
                Models.Confidence8? confidence = null,
                Models.AutotriageVerdict2? autotriageVerdict = null,
                List<string> componentTags = null,
                Models.Exposures2? exposures = null,
                Models.Transitivities2? transitivities = null,
                bool? isMalicious = null,
                Models.ClickToFixPrState? clickToFixPrState = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ApiV1DeploymentsFindingsResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/api/v1/deployments/{deploymentSlug}/findings")
                  .WithAuth("SemgrepWebToken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("deploymentSlug", deploymentSlug).Required())
                      .Query(query => query.Setup("issue_type", (issueType.HasValue) ? CoreHelper.JsonSerialize(issueType.Value).Trim('\"') : "sast"))
                      .Query(query => query.Setup("since", since))
                      .Query(query => query.Setup("page", page ?? 0L))
                      .Query(query => query.Setup("dedup", dedup ?? false))
                      .Query(query => query.Setup("page_size", pageSize ?? 100L))
                      .Query(query => query.Setup("repos", repos))
                      .Query(query => query.Setup("repository_ids", repositoryIds))
                      .Query(query => query.Setup("status", (status.HasValue) ? CoreHelper.JsonSerialize(status.Value).Trim('\"') : null))
                      .Query(query => query.Setup("triage_reasons", (triageReasons.HasValue) ? CoreHelper.JsonSerialize(triageReasons.Value).Trim('\"') : null))
                      .Query(query => query.Setup("severities", (severities.HasValue) ? CoreHelper.JsonSerialize(severities.Value).Trim('\"') : null))
                      .Query(query => query.Setup("ref", mRef))
                      .Query(query => query.Setup("policies", policies))
                      .Query(query => query.Setup("rules", rules))
                      .Query(query => query.Setup("categories", categories))
                      .Query(query => query.Setup("confidence", (confidence.HasValue) ? CoreHelper.JsonSerialize(confidence.Value).Trim('\"') : null))
                      .Query(query => query.Setup("autotriage_verdict", (autotriageVerdict.HasValue) ? CoreHelper.JsonSerialize(autotriageVerdict.Value).Trim('\"') : null))
                      .Query(query => query.Setup("component_tags", componentTags))
                      .Query(query => query.Setup("exposures", (exposures.HasValue) ? CoreHelper.JsonSerialize(exposures.Value).Trim('\"') : null))
                      .Query(query => query.Setup("transitivities", (transitivities.HasValue) ? CoreHelper.JsonSerialize(transitivities.Value).Trim('\"') : null))
                      .Query(query => query.Setup("is_malicious", isMalicious))
                      .Query(query => query.Setup("click_to_fix_pr_state", (clickToFixPrState.HasValue) ? CoreHelper.JsonSerialize(clickToFixPrState.Value).Trim('\"') : null))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}