// <copyright file="Assistant.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Assistant.
    /// </summary>
    public class Assistant
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Assistant"/> class.
        /// </summary>
        public Assistant()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Assistant"/> class.
        /// </summary>
        /// <param name="autofix">autofix.</param>
        /// <param name="autotriage">autotriage.</param>
        /// <param name="component">component.</param>
        /// <param name="guidance">guidance.</param>
        /// <param name="ruleExplanation">rule_explanation.</param>
        public Assistant(
            Models.Autofix autofix = null,
            Models.Autotriage autotriage = null,
            Models.Component component = null,
            Models.Guidance guidance = null,
            Models.RuleExplanation ruleExplanation = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Autofix = autofix;
            this.Autotriage = autotriage;
            this.Component = component;
            this.Guidance = guidance;
            this.RuleExplanation = ruleExplanation;
        }

        /// <summary>
        /// Fix data generated by Semgrep Assistant
        /// </summary>
        [JsonProperty("autofix", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Autofix Autofix { get; set; }

        /// <summary>
        /// Triage recommendation generated by Semgrep Assistant
        /// </summary>
        [JsonProperty("autotriage", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Autotriage Autotriage { get; set; }

        /// <summary>
        /// Semgrep Assistant's guess as for what the matched source code's purpose is
        /// </summary>
        [JsonProperty("component", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Component Component { get; set; }

        /// <summary>
        /// Remediation guidance generated by Semgrep Assistant
        /// </summary>
        [JsonProperty("guidance", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Guidance Guidance { get; set; }

        /// <summary>
        /// AI-generated explanation of why a rule flagged this specific code
        /// </summary>
        [JsonProperty("rule_explanation", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RuleExplanation RuleExplanation { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Assistant : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Autofix = {(this.Autofix == null ? "null" : this.Autofix.ToString())}");
            toStringOutput.Add($"Autotriage = {(this.Autotriage == null ? "null" : this.Autotriage.ToString())}");
            toStringOutput.Add($"Component = {(this.Component == null ? "null" : this.Component.ToString())}");
            toStringOutput.Add($"Guidance = {(this.Guidance == null ? "null" : this.Guidance.ToString())}");
            toStringOutput.Add($"RuleExplanation = {(this.RuleExplanation == null ? "null" : this.RuleExplanation.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}