// <copyright file="AutotriageVerdict.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// AutotriageVerdict.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum AutotriageVerdict
    {
        /// <summary>
        /// TruePositive.
        /// </summary>
        [EnumMember(Value = "true_positive")]
        TruePositive,

        /// <summary>
        /// FalsePositive.
        /// </summary>
        [EnumMember(Value = "false_positive")]
        FalsePositive
    }
}