// <copyright file="BulkTriageRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// BulkTriageRequest.
    /// </summary>
    public class BulkTriageRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BulkTriageRequest"/> class.
        /// </summary>
        public BulkTriageRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BulkTriageRequest"/> class.
        /// </summary>
        /// <param name="issueType">issue_type.</param>
        /// <param name="autotriageVerdict">autotriage_verdict.</param>
        /// <param name="categories">categories.</param>
        /// <param name="componentTags">component_tags.</param>
        /// <param name="confidence">confidence.</param>
        /// <param name="dependencies">dependencies.</param>
        /// <param name="epssProbability">epss_probability.</param>
        /// <param name="exposures">exposures.</param>
        /// <param name="includeHistorical">include_historical.</param>
        /// <param name="issueIds">issue_ids.</param>
        /// <param name="limit">limit.</param>
        /// <param name="newNote">new_note.</param>
        /// <param name="newTriageReason">new_triage_reason.</param>
        /// <param name="newTriageState">new_triage_state.</param>
        /// <param name="policies">policies.</param>
        /// <param name="policyMode">policy_mode.</param>
        /// <param name="proOnly">pro_only.</param>
        /// <param name="projectTags">project_tags.</param>
        /// <param name="mRef">ref.</param>
        /// <param name="repos">repos.</param>
        /// <param name="repositoryVisibility">repository_visibility.</param>
        /// <param name="rules">rules.</param>
        /// <param name="ruleset">ruleset.</param>
        /// <param name="secretTypes">secret_types.</param>
        /// <param name="severities">severities.</param>
        /// <param name="since">since.</param>
        /// <param name="status">status.</param>
        /// <param name="transitivities">transitivities.</param>
        /// <param name="triageReasons">triage_reasons.</param>
        /// <param name="validationState">validation_state.</param>
        public BulkTriageRequest(
            Models.IssueType issueType,
            Models.AutotriageVerdict? autotriageVerdict = null,
            List<string> categories = null,
            List<string> componentTags = null,
            Models.Confidence3? confidence = null,
            List<string> dependencies = null,
            Models.EpssProbability? epssProbability = null,
            Models.Exposures? exposures = null,
            bool? includeHistorical = null,
            List<long> issueIds = null,
            long? limit = 3000L,
            string newNote = null,
            Models.NewTriageReason? newTriageReason = null,
            Models.NewTriageState? newTriageState = null,
            List<string> policies = null,
            Models.PolicyMode1? policyMode = null,
            bool? proOnly = null,
            List<string> projectTags = null,
            string mRef = null,
            List<string> repos = null,
            Models.RepositoryVisibility? repositoryVisibility = null,
            List<string> rules = null,
            List<string> ruleset = null,
            List<string> secretTypes = null,
            Models.Severities? severities = null,
            string since = null,
            Models.Status1? status = null,
            Models.Transitivities? transitivities = null,
            Models.TriageReasons? triageReasons = null,
            Models.ValidationState? validationState = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AutotriageVerdict = autotriageVerdict;
            this.Categories = categories;
            this.ComponentTags = componentTags;
            this.Confidence = confidence;
            this.Dependencies = dependencies;
            this.EpssProbability = epssProbability;
            this.Exposures = exposures;
            this.IncludeHistorical = includeHistorical;
            this.IssueIds = issueIds;
            this.IssueType = issueType;
            this.Limit = limit;
            this.NewNote = newNote;
            this.NewTriageReason = newTriageReason;
            this.NewTriageState = newTriageState;
            this.Policies = policies;
            this.PolicyMode = policyMode;
            this.ProOnly = proOnly;
            this.ProjectTags = projectTags;
            this.MRef = mRef;
            this.Repos = repos;
            this.RepositoryVisibility = repositoryVisibility;
            this.Rules = rules;
            this.Ruleset = ruleset;
            this.SecretTypes = secretTypes;
            this.Severities = severities;
            this.Since = since;
            this.Status = status;
            this.Transitivities = transitivities;
            this.TriageReasons = triageReasons;
            this.ValidationState = validationState;
        }

        /// <summary>
        /// The autotriage verdict to filter by
        /// </summary>
        [JsonProperty("autotriage_verdict", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AutotriageVerdict? AutotriageVerdict { get; set; }

        /// <summary>
        /// List of categories to filter by
        /// </summary>
        [JsonProperty("categories", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Categories { get; set; }

        /// <summary>
        /// List of component tags to filter by
        /// </summary>
        [JsonProperty("component_tags", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ComponentTags { get; set; }

        /// <summary>
        /// List of confidence levels to filter by
        /// </summary>
        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Confidence3? Confidence { get; set; }

        /// <summary>
        /// Filter by dependency name. Only applies for sca findings.
        /// </summary>
        [JsonProperty("dependencies", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Dependencies { get; set; }

        /// <summary>
        /// Filter by EPSS probability (likelihood of exploit). Only applies for sca findings.
        /// </summary>
        [JsonProperty("epss_probability", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EpssProbability? EpssProbability { get; set; }

        /// <summary>
        /// Filter by exposure (reachability type). Only applies for sca findings. Reachability is the ability of an attacker to access a vulnerability in a system.
        /// </summary>
        [JsonProperty("exposures", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Exposures? Exposures { get; set; }

        /// <summary>
        /// Whether to include historical findings. Only applies for secrets findings. Defaults to true.
        /// </summary>
        [JsonProperty("include_historical", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IncludeHistorical { get; set; }

        /// <summary>
        /// An array of issue IDs to act on. If this is not provided, an issue filter should be provided.
        /// </summary>
        [JsonProperty("issue_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> IssueIds { get; set; }

        /// <summary>
        /// Type of findings to bulk triage.
        /// </summary>
        [JsonProperty("issue_type")]
        public Models.IssueType IssueType { get; set; }

        /// <summary>
        /// Max number of issues to triage. Must be an integer between 1 and 3000. Defaults to 3000. When selecting findings to triage, Semgrep will also triage findings with the same fingerprint on other branches. As a result, the list of triaged issue_ids returned in the response may be higher than the specified limit.
        /// </summary>
        [JsonProperty("limit", NullValueHandling = NullValueHandling.Ignore)]
        public long? Limit { get; set; }

        /// <summary>
        /// The note to attach to the bulk triaged findings. Maximum 3000 characters.
        /// </summary>
        [JsonProperty("new_note", NullValueHandling = NullValueHandling.Ignore)]
        public string NewNote { get; set; }

        /// <summary>
        /// The reason for triaging to a given triage state.
        /// </summary>
        [JsonProperty("new_triage_reason", NullValueHandling = NullValueHandling.Ignore)]
        public Models.NewTriageReason? NewTriageReason { get; set; }

        /// <summary>
        /// The triage state you would like to bulk triage your findings to.
        /// </summary>
        [JsonProperty("new_triage_state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.NewTriageState? NewTriageState { get; set; }

        /// <summary>
        /// List of policy modes to filter by
        /// </summary>
        [JsonProperty("policies", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Policies { get; set; }

        /// <summary>
        /// List of policy modes to filter by
        /// </summary>
        [JsonProperty("policy_mode", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PolicyMode1? PolicyMode { get; set; }

        /// <summary>
        /// Filter by whether a finding is only available with Semgrep Pro features.
        /// </summary>
        [JsonProperty("pro_only", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ProOnly { get; set; }

        /// <summary>
        /// List of project tags to filter by
        /// </summary>
        [JsonProperty("project_tags", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ProjectTags { get; set; }

        /// <summary>
        /// Branch reference to filter by
        /// </summary>
        [JsonProperty("ref", NullValueHandling = NullValueHandling.Ignore)]
        public string MRef { get; set; }

        /// <summary>
        /// List of repository names to filter by
        /// </summary>
        [JsonProperty("repos", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Repos { get; set; }

        /// <summary>
        /// Filter by repository visibility. Only applies for secrets findings.
        /// </summary>
        [JsonProperty("repository_visibility", NullValueHandling = NullValueHandling.Ignore)]
        public Models.RepositoryVisibility? RepositoryVisibility { get; set; }

        /// <summary>
        /// List of rule names to filter by
        /// </summary>
        [JsonProperty("rules", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Rules { get; set; }

        /// <summary>
        /// List of Semgrep Registry rulesets to filter by
        /// </summary>
        [JsonProperty("ruleset", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Ruleset { get; set; }

        /// <summary>
        /// Filter by type of secret (typically provider-related). Only applies for secrets findings.
        /// </summary>
        [JsonProperty("secret_types", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> SecretTypes { get; set; }

        /// <summary>
        /// List of severities to filter by
        /// </summary>
        [JsonProperty("severities", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Severities? Severities { get; set; }

        /// <summary>
        /// Epoch timestamp in seconds. Filters using the relevant_since field: the timestamp when this finding was detected by Semgrep (the first time, or when reintroduced).
        /// </summary>
        [JsonProperty("since", NullValueHandling = NullValueHandling.Ignore)]
        public string Since { get; set; }

        /// <summary>
        /// The status to filter by
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status1? Status { get; set; }

        /// <summary>
        /// Filter by transitivity of a dependency. Only applies for sca findings.
        /// </summary>
        [JsonProperty("transitivities", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Transitivities? Transitivities { get; set; }

        /// <summary>
        /// List of triage reasons to filter by
        /// </summary>
        [JsonProperty("triage_reasons", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TriageReasons? TriageReasons { get; set; }

        /// <summary>
        /// Filter by whether a secret could be validated. Only applies for secrets findings.
        /// </summary>
        [JsonProperty("validation_state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ValidationState? ValidationState { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BulkTriageRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AutotriageVerdict = {(this.AutotriageVerdict == null ? "null" : this.AutotriageVerdict.ToString())}");
            toStringOutput.Add($"Categories = {(this.Categories == null ? "null" : $"[{string.Join(", ", this.Categories)} ]")}");
            toStringOutput.Add($"ComponentTags = {(this.ComponentTags == null ? "null" : $"[{string.Join(", ", this.ComponentTags)} ]")}");
            toStringOutput.Add($"Confidence = {(this.Confidence == null ? "null" : this.Confidence.ToString())}");
            toStringOutput.Add($"Dependencies = {(this.Dependencies == null ? "null" : $"[{string.Join(", ", this.Dependencies)} ]")}");
            toStringOutput.Add($"EpssProbability = {(this.EpssProbability == null ? "null" : this.EpssProbability.ToString())}");
            toStringOutput.Add($"Exposures = {(this.Exposures == null ? "null" : this.Exposures.ToString())}");
            toStringOutput.Add($"IncludeHistorical = {(this.IncludeHistorical == null ? "null" : this.IncludeHistorical.ToString())}");
            toStringOutput.Add($"IssueIds = {(this.IssueIds == null ? "null" : $"[{string.Join(", ", this.IssueIds)} ]")}");
            toStringOutput.Add($"IssueType = {this.IssueType}");
            toStringOutput.Add($"Limit = {(this.Limit == null ? "null" : this.Limit.ToString())}");
            toStringOutput.Add($"NewNote = {this.NewNote ?? "null"}");
            toStringOutput.Add($"NewTriageReason = {(this.NewTriageReason == null ? "null" : this.NewTriageReason.ToString())}");
            toStringOutput.Add($"NewTriageState = {(this.NewTriageState == null ? "null" : this.NewTriageState.ToString())}");
            toStringOutput.Add($"Policies = {(this.Policies == null ? "null" : $"[{string.Join(", ", this.Policies)} ]")}");
            toStringOutput.Add($"PolicyMode = {(this.PolicyMode == null ? "null" : this.PolicyMode.ToString())}");
            toStringOutput.Add($"ProOnly = {(this.ProOnly == null ? "null" : this.ProOnly.ToString())}");
            toStringOutput.Add($"ProjectTags = {(this.ProjectTags == null ? "null" : $"[{string.Join(", ", this.ProjectTags)} ]")}");
            toStringOutput.Add($"MRef = {this.MRef ?? "null"}");
            toStringOutput.Add($"Repos = {(this.Repos == null ? "null" : $"[{string.Join(", ", this.Repos)} ]")}");
            toStringOutput.Add($"RepositoryVisibility = {(this.RepositoryVisibility == null ? "null" : this.RepositoryVisibility.ToString())}");
            toStringOutput.Add($"Rules = {(this.Rules == null ? "null" : $"[{string.Join(", ", this.Rules)} ]")}");
            toStringOutput.Add($"Ruleset = {(this.Ruleset == null ? "null" : $"[{string.Join(", ", this.Ruleset)} ]")}");
            toStringOutput.Add($"SecretTypes = {(this.SecretTypes == null ? "null" : $"[{string.Join(", ", this.SecretTypes)} ]")}");
            toStringOutput.Add($"Severities = {(this.Severities == null ? "null" : this.Severities.ToString())}");
            toStringOutput.Add($"Since = {this.Since ?? "null"}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Transitivities = {(this.Transitivities == null ? "null" : this.Transitivities.ToString())}");
            toStringOutput.Add($"TriageReasons = {(this.TriageReasons == null ? "null" : this.TriageReasons.ToString())}");
            toStringOutput.Add($"ValidationState = {(this.ValidationState == null ? "null" : this.ValidationState.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}