// <copyright file="ClickToFixPrState.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ClickToFixPrState.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ClickToFixPrState
    {
        /// <summary>
        /// Open.
        /// </summary>
        [EnumMember(Value = "open")]
        Open,

        /// <summary>
        /// Merged.
        /// </summary>
        [EnumMember(Value = "merged")]
        Merged
    }
}