// <copyright file="Confidence.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Confidence.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Confidence
    {
        /// <summary>
        /// ConfidenceHigh.
        /// </summary>
        [EnumMember(Value = "CONFIDENCE_HIGH")]
        ConfidenceHigh,

        /// <summary>
        /// ConfidenceMedium.
        /// </summary>
        [EnumMember(Value = "CONFIDENCE_MEDIUM")]
        ConfidenceMedium,

        /// <summary>
        /// ConfidenceLow.
        /// </summary>
        [EnumMember(Value = "CONFIDENCE_LOW")]
        ConfidenceLow
    }
}