// <copyright file="Confidence8.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Confidence8.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Confidence8
    {
        /// <summary>
        /// Low.
        /// </summary>
        [EnumMember(Value = "low")]
        Low,

        /// <summary>
        /// Medium.
        /// </summary>
        [EnumMember(Value = "medium")]
        Medium,

        /// <summary>
        /// High.
        /// </summary>
        [EnumMember(Value = "high")]
        High
    }
}