// <copyright file="CreateSbomExportRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// CreateSbomExportRequest.
    /// </summary>
    public class CreateSbomExportRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSbomExportRequest"/> class.
        /// </summary>
        public CreateSbomExportRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSbomExportRequest"/> class.
        /// </summary>
        /// <param name="deploymentId">deploymentId.</param>
        /// <param name="formatVersion">formatVersion.</param>
        /// <param name="metadataComponentType">metadataComponentType.</param>
        /// <param name="metadataSupplier">metadataSupplier.</param>
        /// <param name="mRef">ref.</param>
        /// <param name="repositoryId">repositoryId.</param>
        /// <param name="sbomOutputFormat">sbomOutputFormat.</param>
        public CreateSbomExportRequest(
            string deploymentId,
            Models.ProtosScaV1SbomFormatVersion formatVersion = null,
            Models.MetadataComponentType? metadataComponentType = Models.MetadataComponentType.SbomMetadataComponentTypeCycloneDxV15Application,
            Models.ProtosScaV1SbomMetadataSupplier metadataSupplier = null,
            string mRef = null,
            string repositoryId = null,
            Models.SbomOutputFormat? sbomOutputFormat = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DeploymentId = deploymentId;
            this.FormatVersion = formatVersion;
            this.MetadataComponentType = metadataComponentType;
            this.MetadataSupplier = metadataSupplier;
            this.MRef = mRef;
            this.RepositoryId = repositoryId;
            this.SbomOutputFormat = sbomOutputFormat;
        }

        /// <summary>
        /// Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// Gets or sets FormatVersion.
        /// </summary>
        [JsonProperty("formatVersion", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosScaV1SbomFormatVersion FormatVersion { get; set; }

        /// <summary>
        /// Metadata component type for the SBOM export.
        /// | value | description |
        /// |-------|---------------|
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_APPLICATION |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FRAMEWORK |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_LIBRARY |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_CONTAINER |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_PLATFORM |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_OPERATING_SYSTEM |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE_DRIVER |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FIRMWARE |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FILE |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_MACHINE_LEARNING_MODEL |  |
        /// | SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DATA |  |
        /// </summary>
        [JsonProperty("metadataComponentType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.MetadataComponentType? MetadataComponentType { get; set; }

        /// <summary>
        /// Gets or sets MetadataSupplier.
        /// </summary>
        [JsonProperty("metadataSupplier", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosScaV1SbomMetadataSupplier MetadataSupplier { get; set; }

        /// <summary>
        /// Branch to export SBOM for (Ex. ref=`refs/pull/1234/merge`).
        /// </summary>
        [JsonProperty("ref", NullValueHandling = NullValueHandling.Ignore)]
        public string MRef { get; set; }

        /// <summary>
        /// Repository ID to export SBOM for.
        /// </summary>
        [JsonProperty("repositoryId", NullValueHandling = NullValueHandling.Ignore)]
        public string RepositoryId { get; set; }

        /// <summary>
        /// SBOM output format for the SBOM export.
        /// | value | description |
        /// |-------|---------------|
        /// | SBOM_OUTPUT_FORMAT_JSON |  |
        /// </summary>
        [JsonProperty("sbomOutputFormat", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SbomOutputFormat? SbomOutputFormat { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CreateSbomExportRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"FormatVersion = {(this.FormatVersion == null ? "null" : this.FormatVersion.ToString())}");
            toStringOutput.Add($"MetadataComponentType = {(this.MetadataComponentType == null ? "null" : this.MetadataComponentType.ToString())}");
            toStringOutput.Add($"MetadataSupplier = {(this.MetadataSupplier == null ? "null" : this.MetadataSupplier.ToString())}");
            toStringOutput.Add($"MRef = {this.MRef ?? "null"}");
            toStringOutput.Add($"RepositoryId = {this.RepositoryId ?? "null"}");
            toStringOutput.Add($"SbomOutputFormat = {(this.SbomOutputFormat == null ? "null" : this.SbomOutputFormat.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}