// <copyright file="CyclonedxVersion.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// CyclonedxVersion.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CyclonedxVersion
    {
        /// <summary>
        /// SbomCycloneDxVersionV14.
        /// </summary>
        [EnumMember(Value = "SBOM_CYCLONE_DX_VERSION_V1_4")]
        SbomCycloneDxVersionV14,

        /// <summary>
        /// SbomCycloneDxVersionV15.
        /// </summary>
        [EnumMember(Value = "SBOM_CYCLONE_DX_VERSION_V1_5")]
        SbomCycloneDxVersionV15,

        /// <summary>
        /// SbomCycloneDxVersionV16.
        /// </summary>
        [EnumMember(Value = "SBOM_CYCLONE_DX_VERSION_V1_6")]
        SbomCycloneDxVersionV16,

        /// <summary>
        /// SbomCycloneDxVersionV17.
        /// </summary>
        [EnumMember(Value = "SBOM_CYCLONE_DX_VERSION_V1_7")]
        SbomCycloneDxVersionV17
    }
}