// <copyright file="Ecosystem2.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Ecosystem2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Ecosystem2
    {
        /// <summary>
        /// NoPackageManager.
        /// </summary>
        [EnumMember(Value = "no_package_manager")]
        NoPackageManager,

        /// <summary>
        /// Npm.
        /// </summary>
        [EnumMember(Value = "npm")]
        Npm,

        /// <summary>
        /// Pypi.
        /// </summary>
        [EnumMember(Value = "pypi")]
        Pypi,

        /// <summary>
        /// Gomod.
        /// </summary>
        [EnumMember(Value = "gomod")]
        Gomod,

        /// <summary>
        /// Cargo.
        /// </summary>
        [EnumMember(Value = "cargo")]
        Cargo,

        /// <summary>
        /// Maven.
        /// </summary>
        [EnumMember(Value = "maven")]
        Maven,

        /// <summary>
        /// Gem.
        /// </summary>
        [EnumMember(Value = "gem")]
        Gem,

        /// <summary>
        /// Composer.
        /// </summary>
        [EnumMember(Value = "composer")]
        Composer,

        /// <summary>
        /// Nuget.
        /// </summary>
        [EnumMember(Value = "nuget")]
        Nuget,

        /// <summary>
        /// Pub.
        /// </summary>
        [EnumMember(Value = "pub")]
        Pub,

        /// <summary>
        /// Swiftpm.
        /// </summary>
        [EnumMember(Value = "swiftpm")]
        Swiftpm,

        /// <summary>
        /// Hex.
        /// </summary>
        [EnumMember(Value = "hex")]
        Hex
    }
}