// <copyright file="Exposures.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Exposures.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Exposures
    {
        /// <summary>
        /// Reachable.
        /// </summary>
        [EnumMember(Value = "reachable")]
        Reachable,

        /// <summary>
        /// AlwaysReachable.
        /// </summary>
        [EnumMember(Value = "always_reachable")]
        AlwaysReachable,

        /// <summary>
        /// ConditionallyReachable.
        /// </summary>
        [EnumMember(Value = "conditionally_reachable")]
        ConditionallyReachable,

        /// <summary>
        /// Unreachable.
        /// </summary>
        [EnumMember(Value = "unreachable")]
        Unreachable,

        /// <summary>
        /// Unknown.
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown
    }
}