// <copyright file="FindingLocation.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// FindingLocation.
    /// </summary>
    public class FindingLocation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FindingLocation"/> class.
        /// </summary>
        public FindingLocation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FindingLocation"/> class.
        /// </summary>
        /// <param name="column">column.</param>
        /// <param name="endColumn">end_column.</param>
        /// <param name="endLine">end_line.</param>
        /// <param name="filePath">file_path.</param>
        /// <param name="line">line.</param>
        public FindingLocation(
            long? column = null,
            long? endColumn = null,
            long? endLine = null,
            string filePath = null,
            long? line = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Column = column;
            this.EndColumn = endColumn;
            this.EndLine = endLine;
            this.FilePath = filePath;
            this.Line = line;
        }

        /// <summary>
        /// Column at which the target starts
        /// </summary>
        [JsonProperty("column", NullValueHandling = NullValueHandling.Ignore)]
        public long? Column { get; set; }

        /// <summary>
        /// Column at which the target ends
        /// </summary>
        [JsonProperty("end_column", NullValueHandling = NullValueHandling.Ignore)]
        public long? EndColumn { get; set; }

        /// <summary>
        /// Line at which the target ends
        /// </summary>
        [JsonProperty("end_line", NullValueHandling = NullValueHandling.Ignore)]
        public long? EndLine { get; set; }

        /// <summary>
        /// File path of the relevant line and column numbers
        /// </summary>
        [JsonProperty("file_path", NullValueHandling = NullValueHandling.Ignore)]
        public string FilePath { get; set; }

        /// <summary>
        /// Line at which the target starts
        /// </summary>
        [JsonProperty("line", NullValueHandling = NullValueHandling.Ignore)]
        public long? Line { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FindingLocation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Column = {(this.Column == null ? "null" : this.Column.ToString())}");
            toStringOutput.Add($"EndColumn = {(this.EndColumn == null ? "null" : this.EndColumn.ToString())}");
            toStringOutput.Add($"EndLine = {(this.EndLine == null ? "null" : this.EndLine.ToString())}");
            toStringOutput.Add($"FilePath = {this.FilePath ?? "null"}");
            toStringOutput.Add($"Line = {(this.Line == null ? "null" : this.Line.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}