// <copyright file="FindingRule.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// FindingRule.
    /// </summary>
    public class FindingRule
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FindingRule"/> class.
        /// </summary>
        public FindingRule()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FindingRule"/> class.
        /// </summary>
        /// <param name="category">category.</param>
        /// <param name="confidence">confidence.</param>
        /// <param name="cweNames">cwe_names.</param>
        /// <param name="message">message.</param>
        /// <param name="name">name.</param>
        /// <param name="owaspNames">owasp_names.</param>
        /// <param name="subcategories">subcategories.</param>
        /// <param name="vulnerabilityClasses">vulnerability_classes.</param>
        public FindingRule(
            string category = null,
            Models.Confidence2? confidence = null,
            List<string> cweNames = null,
            string message = null,
            string name = null,
            List<string> owaspNames = null,
            List<string> subcategories = null,
            List<string> vulnerabilityClasses = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Category = category;
            this.Confidence = confidence;
            this.CweNames = cweNames;
            this.Message = message;
            this.Name = name;
            this.OwaspNames = owaspNames;
            this.Subcategories = subcategories;
            this.VulnerabilityClasses = vulnerabilityClasses;
        }

        /// <summary>
        /// Category the rule is associated with
        /// </summary>
        [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
        public string Category { get; set; }

        /// <summary>
        /// Confidence level of the rule
        /// </summary>
        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Confidence2? Confidence { get; set; }

        /// <summary>
        /// CWE names associated with the rule
        /// </summary>
        [JsonProperty("cwe_names", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CweNames { get; set; }

        /// <summary>
        /// Rule message
        /// </summary>
        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public string Message { get; set; }

        /// <summary>
        /// Name of the rule
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// OWASP names associated with the rule
        /// </summary>
        [JsonProperty("owasp_names", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> OwaspNames { get; set; }

        /// <summary>
        /// Subcategories of the rule
        /// </summary>
        [JsonProperty("subcategories", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Subcategories { get; set; }

        /// <summary>
        /// Vulnerability classes the rule is associated with
        /// </summary>
        [JsonProperty("vulnerability_classes", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> VulnerabilityClasses { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FindingRule : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Category = {this.Category ?? "null"}");
            toStringOutput.Add($"Confidence = {(this.Confidence == null ? "null" : this.Confidence.ToString())}");
            toStringOutput.Add($"CweNames = {(this.CweNames == null ? "null" : $"[{string.Join(", ", this.CweNames)} ]")}");
            toStringOutput.Add($"Message = {this.Message ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"OwaspNames = {(this.OwaspNames == null ? "null" : $"[{string.Join(", ", this.OwaspNames)} ]")}");
            toStringOutput.Add($"Subcategories = {(this.Subcategories == null ? "null" : $"[{string.Join(", ", this.Subcategories)} ]")}");
            toStringOutput.Add($"VulnerabilityClasses = {(this.VulnerabilityClasses == null ? "null" : $"[{string.Join(", ", this.VulnerabilityClasses)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}