// <copyright file="Format.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Format.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Format
    {
        /// <summary>
        /// SbomFormatCyclonedx.
        /// </summary>
        [EnumMember(Value = "SBOM_FORMAT_CYCLONEDX")]
        SbomFormatCyclonedx
    }
}