// <copyright file="FoundDependency.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// FoundDependency.
    /// </summary>
    public class FoundDependency
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FoundDependency"/> class.
        /// </summary>
        public FoundDependency()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FoundDependency"/> class.
        /// </summary>
        /// <param name="ecosystem">ecosystem.</param>
        /// <param name="lockfileLineUrl">lockfile_line_url.</param>
        /// <param name="package">package.</param>
        /// <param name="transitivity">transitivity.</param>
        /// <param name="version">version.</param>
        public FoundDependency(
            Models.Ecosystem2? ecosystem = Models.Ecosystem2.NoPackageManager,
            string lockfileLineUrl = null,
            string package = null,
            Models.Transitivity2? transitivity = null,
            string version = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Ecosystem = ecosystem;
            this.LockfileLineUrl = lockfileLineUrl;
            this.Package = package;
            this.Transitivity = transitivity;
            this.Version = version;
        }

        /// <summary>
        /// Ecosystem of the package
        /// </summary>
        [JsonProperty("ecosystem", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Ecosystem2? Ecosystem { get; set; }

        /// <summary>
        /// URL to the specific line in the lockfile where the dependency is listed
        /// </summary>
        [JsonProperty("lockfile_line_url", NullValueHandling = NullValueHandling.Ignore)]
        public string LockfileLineUrl { get; set; }

        /// <summary>
        /// Name of the package that contains the vulnerability
        /// </summary>
        [JsonProperty("package", NullValueHandling = NullValueHandling.Ignore)]
        public string Package { get; set; }

        /// <summary>
        /// Indicates whether the dependency is direct or transitive
        /// </summary>
        [JsonProperty("transitivity", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Transitivity2? Transitivity { get; set; }

        /// <summary>
        /// Version of the package that was found to be vulnerable
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FoundDependency : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Ecosystem = {(this.Ecosystem == null ? "null" : this.Ecosystem.ToString())}");
            toStringOutput.Add($"LockfileLineUrl = {this.LockfileLineUrl ?? "null"}");
            toStringOutput.Add($"Package = {this.Package ?? "null"}");
            toStringOutput.Add($"Transitivity = {(this.Transitivity == null ? "null" : this.Transitivity.ToString())}");
            toStringOutput.Add($"Version = {this.Version ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}