// <copyright file="IssueType.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// IssueType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum IssueType
    {
        /// <summary>
        /// Sast.
        /// </summary>
        [EnumMember(Value = "sast")]
        Sast,

        /// <summary>
        /// Sca.
        /// </summary>
        [EnumMember(Value = "sca")]
        Sca,

        /// <summary>
        /// Secrets.
        /// </summary>
        [EnumMember(Value = "secrets")]
        Secrets
    }
}