// <copyright file="ListLockfilesForDependenciesResponse.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ListLockfilesForDependenciesResponse.
    /// </summary>
    public class ListLockfilesForDependenciesResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListLockfilesForDependenciesResponse"/> class.
        /// </summary>
        public ListLockfilesForDependenciesResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListLockfilesForDependenciesResponse"/> class.
        /// </summary>
        /// <param name="hasMore">hasMore.</param>
        /// <param name="lockfileSummaries">lockfileSummaries.</param>
        /// <param name="cursor">cursor.</param>
        public ListLockfilesForDependenciesResponse(
            bool hasMore,
            List<Models.ProtosScaV1LockfileDependencySummary> lockfileSummaries,
            string cursor = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Cursor = cursor;
            this.HasMore = hasMore;
            this.LockfileSummaries = lockfileSummaries;
        }

        /// <summary>
        /// Pass to next request to get next page of results.
        /// </summary>
        [JsonProperty("cursor", NullValueHandling = NullValueHandling.Ignore)]
        public string Cursor { get; set; }

        /// <summary>
        /// True if there are more lockfiles to get.
        /// </summary>
        [JsonProperty("hasMore")]
        public bool HasMore { get; set; }

        /// <summary>
        /// List of lockfiles.
        /// </summary>
        [JsonProperty("lockfileSummaries")]
        public List<Models.ProtosScaV1LockfileDependencySummary> LockfileSummaries { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListLockfilesForDependenciesResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Cursor = {this.Cursor ?? "null"}");
            toStringOutput.Add($"HasMore = {this.HasMore}");
            toStringOutput.Add($"LockfileSummaries = {(this.LockfileSummaries == null ? "null" : $"[{string.Join(", ", this.LockfileSummaries)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}