// <copyright file="ListDependenciesRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ListDependenciesRequest.
    /// </summary>
    public class ListDependenciesRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListDependenciesRequest"/> class.
        /// </summary>
        public ListDependenciesRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListDependenciesRequest"/> class.
        /// </summary>
        /// <param name="deploymentId">deploymentId.</param>
        /// <param name="cursor">cursor.</param>
        /// <param name="dependencyFilter">dependencyFilter.</param>
        /// <param name="pageSize">pageSize.</param>
        public ListDependenciesRequest(
            string deploymentId,
            string cursor = null,
            Models.ProtosScaV1DependencyFilter dependencyFilter = null,
            long? pageSize = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Cursor = cursor;
            this.DependencyFilter = dependencyFilter;
            this.DeploymentId = deploymentId;
            this.PageSize = pageSize;
        }

        /// <summary>
        /// Cursor to paginate through the dependencies. Provide a cursor value from the response to retrieve the next page.
        /// </summary>
        [JsonProperty("cursor", NullValueHandling = NullValueHandling.Ignore)]
        public string Cursor { get; set; }

        /// <summary>
        /// Object to provide dependency details to filter by.
        /// </summary>
        [JsonProperty("dependencyFilter", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosScaV1DependencyFilter DependencyFilter { get; set; }

        /// <summary>
        /// Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// Number of dependencies per page. Default: 1000, min: 1, max: 10000.
        /// </summary>
        [JsonProperty("pageSize", NullValueHandling = NullValueHandling.Ignore)]
        public long? PageSize { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ListDependenciesRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Cursor = {this.Cursor ?? "null"}");
            toStringOutput.Add($"DependencyFilter = {(this.DependencyFilter == null ? "null" : this.DependencyFilter.ToString())}");
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"PageSize = {(this.PageSize == null ? "null" : this.PageSize.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}