// <copyright file="MetadataComponentType.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// MetadataComponentType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum MetadataComponentType
    {
        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Application.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_APPLICATION")]
        SbomMetadataComponentTypeCycloneDxV15Application,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Framework.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FRAMEWORK")]
        SbomMetadataComponentTypeCycloneDxV15Framework,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Library.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_LIBRARY")]
        SbomMetadataComponentTypeCycloneDxV15Library,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Container.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_CONTAINER")]
        SbomMetadataComponentTypeCycloneDxV15Container,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Platform.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_PLATFORM")]
        SbomMetadataComponentTypeCycloneDxV15Platform,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15OperatingSystem.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_OPERATING_SYSTEM")]
        SbomMetadataComponentTypeCycloneDxV15OperatingSystem,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Device.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE")]
        SbomMetadataComponentTypeCycloneDxV15Device,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15DeviceDriver.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DEVICE_DRIVER")]
        SbomMetadataComponentTypeCycloneDxV15DeviceDriver,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Firmware.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FIRMWARE")]
        SbomMetadataComponentTypeCycloneDxV15Firmware,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15File.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_FILE")]
        SbomMetadataComponentTypeCycloneDxV15File,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15MachineLearningModel.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_MACHINE_LEARNING_MODEL")]
        SbomMetadataComponentTypeCycloneDxV15MachineLearningModel,

        /// <summary>
        /// SbomMetadataComponentTypeCycloneDxV15Data.
        /// </summary>
        [EnumMember(Value = "SBOM_METADATA_COMPONENT_TYPE_CYCLONE_DX_V15_DATA")]
        SbomMetadataComponentTypeCycloneDxV15Data
    }
}