// <copyright file="PolicyMode1.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// PolicyMode1.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum PolicyMode1
    {
        /// <summary>
        /// Monitor.
        /// </summary>
        [EnumMember(Value = "monitor")]
        Monitor,

        /// <summary>
        /// Comment.
        /// </summary>
        [EnumMember(Value = "comment")]
        Comment,

        /// <summary>
        /// Block.
        /// </summary>
        [EnumMember(Value = "block")]
        Block
    }
}