// <copyright file="ProductType.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProductType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProductType
    {
        /// <summary>
        /// ProductTypeSast.
        /// </summary>
        [EnumMember(Value = "PRODUCT_TYPE_SAST")]
        ProductTypeSast,

        /// <summary>
        /// ProductTypeSecrets.
        /// </summary>
        [EnumMember(Value = "PRODUCT_TYPE_SECRETS")]
        ProductTypeSecrets
    }
}