// <copyright file="Products.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Products.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Products
    {
        /// <summary>
        /// ProductSast.
        /// </summary>
        [EnumMember(Value = "PRODUCT_SAST")]
        ProductSast,

        /// <summary>
        /// ProductSca.
        /// </summary>
        [EnumMember(Value = "PRODUCT_SCA")]
        ProductSca,

        /// <summary>
        /// ProductSecrets.
        /// </summary>
        [EnumMember(Value = "PRODUCT_SECRETS")]
        ProductSecrets,

        /// <summary>
        /// ProductAiSast.
        /// </summary>
        [EnumMember(Value = "PRODUCT_AI_SAST")]
        ProductAiSast
    }
}