// <copyright file="Project.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Project.
    /// </summary>
    public class Project
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Project"/> class.
        /// </summary>
        public Project()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Project"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="tags">tags.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="defaultBranch">default_branch.</param>
        /// <param name="latestScanAt">latest_scan_at.</param>
        /// <param name="managedScanConfig">managed_scan_config.</param>
        /// <param name="primaryBranch">primary_branch.</param>
        /// <param name="url">url.</param>
        public Project(
            long id,
            string name,
            List<string> tags,
            string createdAt = null,
            string defaultBranch = null,
            string latestScanAt = null,
            Models.ManagedScanConfig managedScanConfig = null,
            string primaryBranch = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CreatedAt = createdAt;
            this.DefaultBranch = defaultBranch;
            this.Id = id;
            this.LatestScanAt = latestScanAt;
            this.ManagedScanConfig = managedScanConfig;
            this.Name = name;
            this.PrimaryBranch = primaryBranch;
            this.Tags = tags;
            this.Url = url;
        }

        /// <summary>
        /// Time when this project was created.
        /// </summary>
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// The default branch in the SCM.
        /// </summary>
        [JsonProperty("default_branch", NullValueHandling = NullValueHandling.Ignore)]
        public string DefaultBranch { get; set; }

        /// <summary>
        /// Unique ID of this project.
        /// </summary>
        [JsonProperty("id")]
        public long Id { get; set; }

        /// <summary>
        /// Time of latest scan, if there is one.
        /// </summary>
        [JsonProperty("latest_scan_at", NullValueHandling = NullValueHandling.Ignore)]
        public string LatestScanAt { get; set; }

        /// <summary>
        /// [Beta] Configuration of Semgrep Managed Scans for the project, if relevant.
        /// </summary>
        [JsonProperty("managed_scan_config", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ManagedScanConfig ManagedScanConfig { get; set; }

        /// <summary>
        /// Name of the project.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The primary branch of the project, if known.
        /// </summary>
        [JsonProperty("primary_branch", NullValueHandling = NullValueHandling.Ignore)]
        public string PrimaryBranch { get; set; }

        /// <summary>
        /// Tags associated to this project.
        /// </summary>
        [JsonProperty("tags")]
        public List<string> Tags { get; set; }

        /// <summary>
        /// URL of the project, if there is one.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Project : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CreatedAt = {this.CreatedAt ?? "null"}");
            toStringOutput.Add($"DefaultBranch = {this.DefaultBranch ?? "null"}");
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"LatestScanAt = {this.LatestScanAt ?? "null"}");
            toStringOutput.Add($"ManagedScanConfig = {(this.ManagedScanConfig == null ? "null" : this.ManagedScanConfig.ToString())}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"PrimaryBranch = {this.PrimaryBranch ?? "null"}");
            toStringOutput.Add($"Tags = {(this.Tags == null ? "null" : $"[{string.Join(", ", this.Tags)} ]")}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}