// <copyright file="ProtosOpenapiV1UpdatePolicyResponse.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosOpenapiV1UpdatePolicyResponse.
    /// </summary>
    public class ProtosOpenapiV1UpdatePolicyResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1UpdatePolicyResponse"/> class.
        /// </summary>
        public ProtosOpenapiV1UpdatePolicyResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1UpdatePolicyResponse"/> class.
        /// </summary>
        /// <param name="policyId">policyId.</param>
        /// <param name="updatedRule">updatedRule.</param>
        public ProtosOpenapiV1UpdatePolicyResponse(
            string policyId = null,
            Models.Rule updatedRule = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.PolicyId = policyId;
            this.UpdatedRule = updatedRule;
        }

        /// <summary>
        /// Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`.
        /// </summary>
        [JsonProperty("policyId", NullValueHandling = NullValueHandling.Ignore)]
        public string PolicyId { get; set; }

        /// <summary>
        /// Gets or sets UpdatedRule.
        /// </summary>
        [JsonProperty("updatedRule", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Rule UpdatedRule { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosOpenapiV1UpdatePolicyResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PolicyId = {this.PolicyId ?? "null"}");
            toStringOutput.Add($"UpdatedRule = {(this.UpdatedRule == null ? "null" : this.UpdatedRule.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}