// <copyright file="ProtosScaV1SbomFormatVersion.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosScaV1SbomFormatVersion.
    /// </summary>
    public class ProtosScaV1SbomFormatVersion
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1SbomFormatVersion"/> class.
        /// </summary>
        public ProtosScaV1SbomFormatVersion()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1SbomFormatVersion"/> class.
        /// </summary>
        /// <param name="cyclonedxVersion">cyclonedxVersion.</param>
        /// <param name="format">format.</param>
        /// <param name="version">version.</param>
        public ProtosScaV1SbomFormatVersion(
            Models.CyclonedxVersion? cyclonedxVersion = null,
            Models.Format? format = Models.Format.SbomFormatCyclonedx,
            string version = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CyclonedxVersion = cyclonedxVersion;
            this.Format = format;
            this.Version = version;
        }

        /// <summary>
        /// CycloneDX schema version for the SBOM export. Supported: 1.4, 1.5, 1.6, 1.7. Defaults to 1.4 when unset.
        /// | value | description |
        /// |-------|---------------|
        /// | SBOM_CYCLONE_DX_VERSION_V1_4 |  |
        /// | SBOM_CYCLONE_DX_VERSION_V1_5 |  |
        /// | SBOM_CYCLONE_DX_VERSION_V1_6 |  |
        /// | SBOM_CYCLONE_DX_VERSION_V1_7 |  |
        /// </summary>
        [JsonProperty("cyclonedxVersion", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CyclonedxVersion? CyclonedxVersion { get; set; }

        /// <summary>
        /// Format for the SBOM export.
        /// | value | description |
        /// |-------|---------------|
        /// | SBOM_FORMAT_CYCLONEDX |  |
        /// </summary>
        [JsonProperty("format", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Format? Format { get; set; }

        /// <summary>
        /// Deprecated. Use `cyclonedx_version`. Free-text CycloneDX version, e.g. "1.7".
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public string Version { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosScaV1SbomFormatVersion : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CyclonedxVersion = {(this.CyclonedxVersion == null ? "null" : this.CyclonedxVersion.ToString())}");
            toStringOutput.Add($"Format = {(this.Format == null ? "null" : this.Format.ToString())}");
            toStringOutput.Add($"Version = {this.Version ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}