// <copyright file="ProtosScanV1ScanPublic.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosScanV1ScanPublic.
    /// </summary>
    public class ProtosScanV1ScanPublic
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScanV1ScanPublic"/> class.
        /// </summary>
        public ProtosScanV1ScanPublic()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScanV1ScanPublic"/> class.
        /// </summary>
        /// <param name="branch">branch.</param>
        /// <param name="commit">commit.</param>
        /// <param name="completedAt">completed_at.</param>
        /// <param name="deploymentId">deployment_id.</param>
        /// <param name="enabledProducts">enabled_products.</param>
        /// <param name="exitCode">exit_code.</param>
        /// <param name="findingsCounts">findings_counts.</param>
        /// <param name="id">id.</param>
        /// <param name="isFullScan">is_full_scan.</param>
        /// <param name="repositoryId">repository_id.</param>
        /// <param name="startedAt">started_at.</param>
        /// <param name="status">status.</param>
        /// <param name="totalTime">total_time.</param>
        public ProtosScanV1ScanPublic(
            string branch = null,
            string commit = null,
            DateTime? completedAt = null,
            string deploymentId = null,
            List<string> enabledProducts = null,
            string exitCode = null,
            Models.ProtosScanV1ScanFindingsCounts findingsCounts = null,
            string id = null,
            bool? isFullScan = null,
            string repositoryId = null,
            DateTime? startedAt = null,
            Models.Status7? status = null,
            double? totalTime = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Branch = branch;
            this.Commit = commit;
            this.CompletedAt = completedAt;
            this.DeploymentId = deploymentId;
            this.EnabledProducts = enabledProducts;
            this.ExitCode = exitCode;
            this.FindingsCounts = findingsCounts;
            this.Id = id;
            this.IsFullScan = isFullScan;
            this.RepositoryId = repositoryId;
            this.StartedAt = startedAt;
            this.Status = status;
            this.TotalTime = totalTime;
        }

        /// <summary>
        /// The scanned branch
        /// </summary>
        [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
        public string Branch { get; set; }

        /// <summary>
        /// The commit hash that was scanned
        /// </summary>
        [JsonProperty("commit", NullValueHandling = NullValueHandling.Ignore)]
        public string Commit { get; set; }

        /// <summary>
        /// The timestamp when this scan completed (if it has completed).
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("completed_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? CompletedAt { get; set; }

        /// <summary>
        /// Unique identifier for the deployment of the scan.
        /// </summary>
        [JsonProperty("deployment_id", NullValueHandling = NullValueHandling.Ignore)]
        public string DeploymentId { get; set; }

        /// <summary>
        /// The products used when running the scan.
        /// </summary>
        [JsonProperty("enabled_products", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> EnabledProducts { get; set; }

        /// <summary>
        /// The exit_code of the scan (see https://semgrep.dev/docs/cli-reference#exit-codes)
        /// </summary>
        [JsonProperty("exit_code", NullValueHandling = NullValueHandling.Ignore)]
        public string ExitCode { get; set; }

        /// <summary>
        /// Gets or sets FindingsCounts.
        /// </summary>
        [JsonProperty("findings_counts", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosScanV1ScanFindingsCounts FindingsCounts { get; set; }

        /// <summary>
        /// ID of the scan.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Whether the scan was a full scan (true) or a diff scan (false)
        /// </summary>
        [JsonProperty("is_full_scan", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsFullScan { get; set; }

        /// <summary>
        /// Unique identifier for the repository of the scan.
        /// </summary>
        [JsonProperty("repository_id", NullValueHandling = NullValueHandling.Ignore)]
        public string RepositoryId { get; set; }

        /// <summary>
        /// The timestamp when this scan started.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? StartedAt { get; set; }

        /// <summary>
        /// The current status of the scan
        /// | value | description |
        /// |-------|---------------|
        /// | SCAN_STATUS_RUNNING | The scan is currently running |
        /// | SCAN_STATUS_COMPLETED | The scan has completed successfully (0 or 1 exit code) |
        /// | SCAN_STATUS_PENDING | The scan is queued and waiting to start |
        /// | SCAN_STATUS_CANCELLED | The scan was cancelled before completion |
        /// | SCAN_STATUS_ERROR | The scan has exited with a failure (exit code not 0 or 1) |
        /// | SCAN_STATUS_NEVER_FINISHED | The scan did not report an error or success after over an hour |
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status7? Status { get; set; }

        /// <summary>
        /// Duration of scan, in seconds
        /// </summary>
        [JsonProperty("total_time", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosScanV1ScanPublic : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Branch = {this.Branch ?? "null"}");
            toStringOutput.Add($"Commit = {this.Commit ?? "null"}");
            toStringOutput.Add($"CompletedAt = {(this.CompletedAt == null ? "null" : this.CompletedAt.ToString())}");
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"EnabledProducts = {(this.EnabledProducts == null ? "null" : $"[{string.Join(", ", this.EnabledProducts)} ]")}");
            toStringOutput.Add($"ExitCode = {this.ExitCode ?? "null"}");
            toStringOutput.Add($"FindingsCounts = {(this.FindingsCounts == null ? "null" : this.FindingsCounts.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"IsFullScan = {(this.IsFullScan == null ? "null" : this.IsFullScan.ToString())}");
            toStringOutput.Add($"RepositoryId = {this.RepositoryId ?? "null"}");
            toStringOutput.Add($"StartedAt = {(this.StartedAt == null ? "null" : this.StartedAt.ToString())}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"TotalTime = {(this.TotalTime == null ? "null" : this.TotalTime.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}