// <copyright file="ProtosScaV1RepositoryDependencySummary.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosScaV1RepositoryDependencySummary.
    /// </summary>
    public class ProtosScaV1RepositoryDependencySummary
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1RepositoryDependencySummary"/> class.
        /// </summary>
        public ProtosScaV1RepositoryDependencySummary()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1RepositoryDependencySummary"/> class.
        /// </summary>
        /// <param name="hasDependencyPathScan">hasDependencyPathScan.</param>
        /// <param name="id">id.</param>
        /// <param name="name">name.</param>
        /// <param name="numDependencies">numDependencies.</param>
        public ProtosScaV1RepositoryDependencySummary(
            bool? hasDependencyPathScan = null,
            long? id = null,
            string name = null,
            long? numDependencies = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.HasDependencyPathScan = hasDependencyPathScan;
            this.Id = id;
            this.Name = name;
            this.NumDependencies = numDependencies;
        }

        /// <summary>
        /// True if the repository has been scanned with the `hasPathToTransitivityInScans` feature flag
        ///  which means it will have dependency graph data in DGraph available to query
        /// </summary>
        [JsonProperty("hasDependencyPathScan", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasDependencyPathScan { get; set; }

        /// <summary>
        /// ID of repository.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        /// <summary>
        /// Name of repository.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Total number of dependencies in the repository.
        /// </summary>
        [JsonProperty("numDependencies", NullValueHandling = NullValueHandling.Ignore)]
        public long? NumDependencies { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosScaV1RepositoryDependencySummary : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"HasDependencyPathScan = {(this.HasDependencyPathScan == null ? "null" : this.HasDependencyPathScan.ToString())}");
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"NumDependencies = {(this.NumDependencies == null ? "null" : this.NumDependencies.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}