// <copyright file="ProtosOpenapiV1LinkTicketResponse.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosOpenapiV1LinkTicketResponse.
    /// </summary>
    public class ProtosOpenapiV1LinkTicketResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1LinkTicketResponse"/> class.
        /// </summary>
        public ProtosOpenapiV1LinkTicketResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1LinkTicketResponse"/> class.
        /// </summary>
        /// <param name="externalSlug">external_slug.</param>
        /// <param name="linkedIssueIds">linked_issue_ids.</param>
        /// <param name="replacedIssueIds">replaced_issue_ids.</param>
        /// <param name="ticketId">ticket_id.</param>
        /// <param name="ticketUrl">ticket_url.</param>
        public ProtosOpenapiV1LinkTicketResponse(
            string externalSlug = null,
            List<string> linkedIssueIds = null,
            List<string> replacedIssueIds = null,
            long? ticketId = null,
            string ticketUrl = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ExternalSlug = externalSlug;
            this.LinkedIssueIds = linkedIssueIds;
            this.ReplacedIssueIds = replacedIssueIds;
            this.TicketId = ticketId;
            this.TicketUrl = ticketUrl;
        }

        /// <summary>
        /// The external slug identifier for the ticket (e.g. SEC-123)
        /// </summary>
        [JsonProperty("external_slug", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalSlug { get; set; }

        /// <summary>
        /// List of finding IDs that were successfully linked to the ticket
        /// </summary>
        [JsonProperty("linked_issue_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> LinkedIssueIds { get; set; }

        /// <summary>
        /// List of finding IDs where an existing ticket link was replaced
        /// </summary>
        [JsonProperty("replaced_issue_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ReplacedIssueIds { get; set; }

        /// <summary>
        /// The internal ID of the linked ticket record
        /// </summary>
        [JsonProperty("ticket_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? TicketId { get; set; }

        /// <summary>
        /// The URL of the linked ticket
        /// </summary>
        [JsonProperty("ticket_url", NullValueHandling = NullValueHandling.Ignore)]
        public string TicketUrl { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosOpenapiV1LinkTicketResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExternalSlug = {this.ExternalSlug ?? "null"}");
            toStringOutput.Add($"LinkedIssueIds = {(this.LinkedIssueIds == null ? "null" : $"[{string.Join(", ", this.LinkedIssueIds)} ]")}");
            toStringOutput.Add($"ReplacedIssueIds = {(this.ReplacedIssueIds == null ? "null" : $"[{string.Join(", ", this.ReplacedIssueIds)} ]")}");
            toStringOutput.Add($"TicketId = {(this.TicketId == null ? "null" : this.TicketId.ToString())}");
            toStringOutput.Add($"TicketUrl = {this.TicketUrl ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}