// <copyright file="ProtosOpenapiV1GetScanResponse.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosOpenapiV1GetScanResponse.
    /// </summary>
    public class ProtosOpenapiV1GetScanResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1GetScanResponse"/> class.
        /// </summary>
        public ProtosOpenapiV1GetScanResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1GetScanResponse"/> class.
        /// </summary>
        /// <param name="completedAt">completed_at.</param>
        /// <param name="deploymentId">deployment_id.</param>
        /// <param name="enabledProducts">enabled_products.</param>
        /// <param name="exitCode">exit_code.</param>
        /// <param name="hasLogs">has_logs.</param>
        /// <param name="id">id.</param>
        /// <param name="meta">meta.</param>
        /// <param name="repositoryId">repository_id.</param>
        /// <param name="startedAt">started_at.</param>
        /// <param name="stats">stats.</param>
        public ProtosOpenapiV1GetScanResponse(
            string completedAt = null,
            long? deploymentId = null,
            List<string> enabledProducts = null,
            long? exitCode = null,
            bool? hasLogs = null,
            long? id = null,
            Models.ProtosOpenapiV1GetScanResponseScanMeta meta = null,
            long? repositoryId = null,
            string startedAt = null,
            object stats = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CompletedAt = completedAt;
            this.DeploymentId = deploymentId;
            this.EnabledProducts = enabledProducts;
            this.ExitCode = exitCode;
            this.HasLogs = hasLogs;
            this.Id = id;
            this.Meta = meta;
            this.RepositoryId = repositoryId;
            this.StartedAt = startedAt;
            this.Stats = stats;
        }

        /// <summary>
        /// imestamp of when the scan started.
        /// </summary>
        [JsonProperty("completed_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CompletedAt { get; set; }

        /// <summary>
        /// The unique ID of the deployment associated with the scanned repository.
        /// </summary>
        [JsonProperty("deployment_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? DeploymentId { get; set; }

        /// <summary>
        /// The products used when running the scan.
        /// </summary>
        [JsonProperty("enabled_products", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> EnabledProducts { get; set; }

        /// <summary>
        /// Gets or sets ExitCode.
        /// </summary>
        [JsonProperty("exit_code", NullValueHandling = NullValueHandling.Ignore)]
        public long? ExitCode { get; set; }

        /// <summary>
        /// Gets or sets HasLogs.
        /// </summary>
        [JsonProperty("has_logs", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasLogs { get; set; }

        /// <summary>
        /// The unique ID representing this scan.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        /// <summary>
        /// Gets or sets Meta.
        /// </summary>
        [JsonProperty("meta", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosOpenapiV1GetScanResponseScanMeta Meta { get; set; }

        /// <summary>
        /// The unique ID of the repository that was scanned.
        /// </summary>
        [JsonProperty("repository_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? RepositoryId { get; set; }

        /// <summary>
        /// when the scan was started
        /// </summary>
        [JsonProperty("started_at", NullValueHandling = NullValueHandling.Ignore)]
        public string StartedAt { get; set; }

        /// <summary>
        /// Miscellaneous statistics about the scan, like number of findings found and scan duration.
        /// </summary>
        [JsonProperty("stats", NullValueHandling = NullValueHandling.Ignore)]
        public object Stats { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosOpenapiV1GetScanResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CompletedAt = {this.CompletedAt ?? "null"}");
            toStringOutput.Add($"DeploymentId = {(this.DeploymentId == null ? "null" : this.DeploymentId.ToString())}");
            toStringOutput.Add($"EnabledProducts = {(this.EnabledProducts == null ? "null" : $"[{string.Join(", ", this.EnabledProducts)} ]")}");
            toStringOutput.Add($"ExitCode = {(this.ExitCode == null ? "null" : this.ExitCode.ToString())}");
            toStringOutput.Add($"HasLogs = {(this.HasLogs == null ? "null" : this.HasLogs.ToString())}");
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"Meta = {(this.Meta == null ? "null" : this.Meta.ToString())}");
            toStringOutput.Add($"RepositoryId = {(this.RepositoryId == null ? "null" : this.RepositoryId.ToString())}");
            toStringOutput.Add($"StartedAt = {this.StartedAt ?? "null"}");
            toStringOutput.Add($"Stats = {(this.Stats == null ? "null" : this.Stats.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}