// <copyright file="ProtosScaV1PackageFilter.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosScaV1PackageFilter.
    /// </summary>
    public class ProtosScaV1PackageFilter
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1PackageFilter"/> class.
        /// </summary>
        public ProtosScaV1PackageFilter()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1PackageFilter"/> class.
        /// </summary>
        /// <param name="exactNameMatch">exactNameMatch.</param>
        /// <param name="exactVersion">exactVersion.</param>
        /// <param name="name">name.</param>
        /// <param name="versionLowerBound">versionLowerBound.</param>
        /// <param name="versionUpperBound">versionUpperBound.</param>
        public ProtosScaV1PackageFilter(
            bool? exactNameMatch = null,
            string exactVersion = null,
            string name = null,
            string versionLowerBound = null,
            string versionUpperBound = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ExactNameMatch = exactNameMatch;
            this.ExactVersion = exactVersion;
            this.Name = name;
            this.VersionLowerBound = versionLowerBound;
            this.VersionUpperBound = versionUpperBound;
        }

        /// <summary>
        /// When true, name must match exactly. When false (default), name is fuzzy-matched (contains).
        /// </summary>
        [JsonProperty("exactNameMatch", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ExactNameMatch { get; set; }

        /// <summary>
        /// Exact version match (e.g. "1.0.0").
        ///  Takes precedence over version bounds if set.
        /// </summary>
        [JsonProperty("exactVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string ExactVersion { get; set; }

        /// <summary>
        /// Exact package name (e.g. lodash).
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Lower bound version constraint (e.g. ">=1.0.0").
        ///  Ignored if exact_version is set.
        /// </summary>
        [JsonProperty("versionLowerBound", NullValueHandling = NullValueHandling.Ignore)]
        public string VersionLowerBound { get; set; }

        /// <summary>
        /// <![CDATA[
        /// Upper bound version constraint (e.g. "<2.0.0").
        ///  Ignored if exact_version is set.
        /// ]]>
        /// </summary>
        [JsonProperty("versionUpperBound", NullValueHandling = NullValueHandling.Ignore)]
        public string VersionUpperBound { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosScaV1PackageFilter : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExactNameMatch = {(this.ExactNameMatch == null ? "null" : this.ExactNameMatch.ToString())}");
            toStringOutput.Add($"ExactVersion = {this.ExactVersion ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"VersionLowerBound = {this.VersionLowerBound ?? "null"}");
            toStringOutput.Add($"VersionUpperBound = {this.VersionUpperBound ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}