// <copyright file="ProtosOpenapiV1GetBootstrapSmsVpcResponse.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosOpenapiV1GetBootstrapSmsVpcResponse.
    /// </summary>
    public class ProtosOpenapiV1GetBootstrapSmsVpcResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1GetBootstrapSmsVpcResponse"/> class.
        /// </summary>
        public ProtosOpenapiV1GetBootstrapSmsVpcResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1GetBootstrapSmsVpcResponse"/> class.
        /// </summary>
        /// <param name="awsTemplateFormatVersion">AWSTemplateFormatVersion.</param>
        /// <param name="description">Description.</param>
        /// <param name="metadata">Metadata.</param>
        /// <param name="outputs">Outputs.</param>
        /// <param name="parameters">Parameters.</param>
        /// <param name="resources">Resources.</param>
        public ProtosOpenapiV1GetBootstrapSmsVpcResponse(
            string awsTemplateFormatVersion = null,
            string description = null,
            object metadata = null,
            object outputs = null,
            object parameters = null,
            object resources = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AwsTemplateFormatVersion = awsTemplateFormatVersion;
            this.Description = description;
            this.Metadata = metadata;
            this.Outputs = outputs;
            this.Parameters = parameters;
            this.Resources = resources;
        }

        /// <summary>
        /// The AWSTemplateFormatVersion that the template conforms to
        /// </summary>
        [JsonProperty("AWSTemplateFormatVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string AwsTemplateFormatVersion { get; set; }

        /// <summary>
        /// Template description
        /// </summary>
        [JsonProperty("Description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        /// <summary>
        /// Template metadata including version and last updated date
        /// </summary>
        [JsonProperty("Metadata", NullValueHandling = NullValueHandling.Ignore)]
        public object Metadata { get; set; }

        /// <summary>
        /// Output values of the stack
        /// </summary>
        [JsonProperty("Outputs", NullValueHandling = NullValueHandling.Ignore)]
        public object Outputs { get; set; }

        /// <summary>
        /// Template parameters
        /// </summary>
        [JsonProperty("Parameters", NullValueHandling = NullValueHandling.Ignore)]
        public object Parameters { get; set; }

        /// <summary>
        /// Declaration of AWS resources
        /// </summary>
        [JsonProperty("Resources", NullValueHandling = NullValueHandling.Ignore)]
        public object Resources { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosOpenapiV1GetBootstrapSmsVpcResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AwsTemplateFormatVersion = {this.AwsTemplateFormatVersion ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"Metadata = {(this.Metadata == null ? "null" : this.Metadata.ToString())}");
            toStringOutput.Add($"Outputs = {(this.Outputs == null ? "null" : this.Outputs.ToString())}");
            toStringOutput.Add($"Parameters = {(this.Parameters == null ? "null" : this.Parameters.ToString())}");
            toStringOutput.Add($"Resources = {(this.Resources == null ? "null" : this.Resources.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}