// <copyright file="ProtosAiV1Autotriage.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosAiV1Autotriage.
    /// </summary>
    public class ProtosAiV1Autotriage
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosAiV1Autotriage"/> class.
        /// </summary>
        public ProtosAiV1Autotriage()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosAiV1Autotriage"/> class.
        /// </summary>
        /// <param name="feedback">feedback.</param>
        /// <param name="id">id.</param>
        /// <param name="issueId">issueId.</param>
        /// <param name="matchBasedId">matchBasedId.</param>
        /// <param name="memoryIdsReferenced">memoryIdsReferenced.</param>
        /// <param name="memoryIdsRendered">memoryIdsRendered.</param>
        /// <param name="reason">reason.</param>
        /// <param name="verdict">verdict.</param>
        public ProtosAiV1Autotriage(
            Models.ProtosAiV1AutotriageFeedback feedback = null,
            string id = null,
            string issueId = null,
            string matchBasedId = null,
            List<string> memoryIdsReferenced = null,
            List<string> memoryIdsRendered = null,
            string reason = null,
            Models.Verdict? verdict = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Feedback = feedback;
            this.Id = id;
            this.IssueId = issueId;
            this.MatchBasedId = matchBasedId;
            this.MemoryIdsReferenced = memoryIdsReferenced;
            this.MemoryIdsRendered = memoryIdsRendered;
            this.Reason = reason;
            this.Verdict = verdict;
        }

        /// <summary>
        /// Gets or sets Feedback.
        /// </summary>
        [JsonProperty("feedback", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosAiV1AutotriageFeedback Feedback { get; set; }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets IssueId.
        /// </summary>
        [JsonProperty("issueId", NullValueHandling = NullValueHandling.Ignore)]
        public string IssueId { get; set; }

        /// <summary>
        /// Gets or sets MatchBasedId.
        /// </summary>
        [JsonProperty("matchBasedId", NullValueHandling = NullValueHandling.Ignore)]
        public string MatchBasedId { get; set; }

        /// <summary>
        /// Gets or sets MemoryIdsReferenced.
        /// </summary>
        [JsonProperty("memoryIdsReferenced", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> MemoryIdsReferenced { get; set; }

        /// <summary>
        /// Gets or sets MemoryIdsRendered.
        /// </summary>
        [JsonProperty("memoryIdsRendered", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> MemoryIdsRendered { get; set; }

        /// <summary>
        /// The reasoning for a false positive verdict, explaining why you might want to ignore the finding. Empty string if verdict is true positive.
        /// </summary>
        [JsonProperty("reason", NullValueHandling = NullValueHandling.Ignore)]
        public string Reason { get; set; }

        /// <summary>
        /// | value | description |
        /// |-------|---------------|
        /// | VERDICT_TRUE_POSITIVE |  |
        /// | VERDICT_FALSE_POSITIVE |  |
        /// | VERDICT_NO_VERDICT |  |
        /// </summary>
        [JsonProperty("verdict", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Verdict? Verdict { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosAiV1Autotriage : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Feedback = {(this.Feedback == null ? "null" : this.Feedback.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"IssueId = {this.IssueId ?? "null"}");
            toStringOutput.Add($"MatchBasedId = {this.MatchBasedId ?? "null"}");
            toStringOutput.Add($"MemoryIdsReferenced = {(this.MemoryIdsReferenced == null ? "null" : $"[{string.Join(", ", this.MemoryIdsReferenced)} ]")}");
            toStringOutput.Add($"MemoryIdsRendered = {(this.MemoryIdsRendered == null ? "null" : $"[{string.Join(", ", this.MemoryIdsRendered)} ]")}");
            toStringOutput.Add($"Reason = {this.Reason ?? "null"}");
            toStringOutput.Add($"Verdict = {(this.Verdict == null ? "null" : this.Verdict.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}