// <copyright file="ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess.
    /// </summary>
    public class ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess"/> class.
        /// </summary>
        public ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess"/> class.
        /// </summary>
        /// <param name="externalSlug">external_slug.</param>
        /// <param name="issueIds">issue_ids.</param>
        /// <param name="ticketId">ticket_id.</param>
        /// <param name="ticketUrl">ticket_url.</param>
        public ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess(
            string externalSlug = null,
            List<long> issueIds = null,
            long? ticketId = null,
            string ticketUrl = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ExternalSlug = externalSlug;
            this.IssueIds = issueIds;
            this.TicketId = ticketId;
            this.TicketUrl = ticketUrl;
        }

        /// <summary>
        /// The external slug identifier for the ticket
        /// </summary>
        [JsonProperty("external_slug", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalSlug { get; set; }

        /// <summary>
        /// List of issue IDs
        /// </summary>
        [JsonProperty("issue_ids", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> IssueIds { get; set; }

        /// <summary>
        /// The ID of the created ticket
        /// </summary>
        [JsonProperty("ticket_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? TicketId { get; set; }

        /// <summary>
        /// The URL of the created ticket
        /// </summary>
        [JsonProperty("ticket_url", NullValueHandling = NullValueHandling.Ignore)]
        public string TicketUrl { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosOpenapiV1CreateTicketResponseTicketCreationSuccess : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExternalSlug = {this.ExternalSlug ?? "null"}");
            toStringOutput.Add($"IssueIds = {(this.IssueIds == null ? "null" : $"[{string.Join(", ", this.IssueIds)} ]")}");
            toStringOutput.Add($"TicketId = {(this.TicketId == null ? "null" : this.TicketId.ToString())}");
            toStringOutput.Add($"TicketUrl = {this.TicketUrl ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}