// <copyright file="ProtosSecretsV1SecretsFindingRepository.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosSecretsV1SecretsFindingRepository.
    /// </summary>
    public class ProtosSecretsV1SecretsFindingRepository
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosSecretsV1SecretsFindingRepository"/> class.
        /// </summary>
        public ProtosSecretsV1SecretsFindingRepository()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosSecretsV1SecretsFindingRepository"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="scmType">scmType.</param>
        /// <param name="url">url.</param>
        /// <param name="visibility">visibility.</param>
        public ProtosSecretsV1SecretsFindingRepository(
            string name = null,
            Models.ScmType? scmType = null,
            string url = null,
            Models.Visibility? visibility = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Name = name;
            this.ScmType = scmType;
            this.Url = url;
            this.Visibility = visibility;
        }

        /// <summary>
        /// Repository name
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Provider for the finding (e.g. GitHub, GitLab, GHE, etc).
        /// | value | description |
        /// |-------|---------------|
        /// | SCM_TYPE_GITHUB | GitHub Cloud |
        /// | SCM_TYPE_GITHUB_ENTERPRISE | GitHub Enterprise |
        /// | SCM_TYPE_GITLAB | GitLab Cloud |
        /// | SCM_TYPE_GITLAB_SELFMANAGED | GitLab Self-Managed |
        /// | SCM_TYPE_BITBUCKET | Bitbucket Cloud |
        /// | SCM_TYPE_BITBUCKET_DATACENTER | Bitbucket Data Center |
        /// | SCM_TYPE_AZURE_DEVOPS | Azure DevOps |
        /// | SCM_TYPE_UNKNOWN |  |
        /// | SCM_TYPE_HARNESS | Harness |
        /// </summary>
        [JsonProperty("scmType", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ScmType? ScmType { get; set; }

        /// <summary>
        /// URL to the repository where the finding was detected.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <summary>
        /// Repository visbility (e.g. public, private, unknown).
        /// | value | description |
        /// |-------|---------------|
        /// | REPOSITORY_VISIBILITY_PUBLIC |  |
        /// | REPOSITORY_VISIBILITY_PRIVATE |  |
        /// | REPOSITORY_VISIBILITY_UNKNOWN |  |
        /// </summary>
        [JsonProperty("visibility", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Visibility? Visibility { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosSecretsV1SecretsFindingRepository : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"ScmType = {(this.ScmType == null ? "null" : this.ScmType.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Visibility = {(this.Visibility == null ? "null" : this.Visibility.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}