// <copyright file="ProtosTicketingV1ExternalTicket.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosTicketingV1ExternalTicket.
    /// </summary>
    public class ProtosTicketingV1ExternalTicket
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosTicketingV1ExternalTicket"/> class.
        /// </summary>
        public ProtosTicketingV1ExternalTicket()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosTicketingV1ExternalTicket"/> class.
        /// </summary>
        /// <param name="externalSlug">externalSlug.</param>
        /// <param name="id">id.</param>
        /// <param name="linkedIssueIds">linkedIssueIds.</param>
        /// <param name="url">url.</param>
        public ProtosTicketingV1ExternalTicket(
            string externalSlug = null,
            string id = null,
            List<string> linkedIssueIds = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ExternalSlug = externalSlug;
            this.Id = id;
            this.LinkedIssueIds = linkedIssueIds;
            this.Url = url;
        }

        /// <summary>
        /// Identifier of the external ticket (e.g. for Jira, something like OPS-158).
        /// </summary>
        [JsonProperty("externalSlug", NullValueHandling = NullValueHandling.Ignore)]
        public string ExternalSlug { get; set; }

        /// <summary>
        /// Nango ticket id
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Semgrep issue ids that are linked to this external ticket
        /// </summary>
        [JsonProperty("linkedIssueIds", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> LinkedIssueIds { get; set; }

        /// <summary>
        /// URL of the external ticket.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosTicketingV1ExternalTicket : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExternalSlug = {this.ExternalSlug ?? "null"}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"LinkedIssueIds = {(this.LinkedIssueIds == null ? "null" : $"[{string.Join(", ", this.LinkedIssueIds)} ]")}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}