// <copyright file="ProtosScaV1CodeLocation.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ProtosScaV1CodeLocation.
    /// </summary>
    public class ProtosScaV1CodeLocation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1CodeLocation"/> class.
        /// </summary>
        public ProtosScaV1CodeLocation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProtosScaV1CodeLocation"/> class.
        /// </summary>
        /// <param name="committedAt">committedAt.</param>
        /// <param name="endCol">endCol.</param>
        /// <param name="endLine">endLine.</param>
        /// <param name="path">path.</param>
        /// <param name="startCol">startCol.</param>
        /// <param name="startLine">startLine.</param>
        /// <param name="url">url.</param>
        public ProtosScaV1CodeLocation(
            DateTime? committedAt = null,
            string endCol = null,
            string endLine = null,
            string path = null,
            string startCol = null,
            string startLine = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.CommittedAt = committedAt;
            this.EndCol = endCol;
            this.EndLine = endLine;
            this.Path = path;
            this.StartCol = startCol;
            this.StartLine = startLine;
            this.Url = url;
        }

        /// <summary>
        /// Timestamp when code file was last modified, if available.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("committedAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? CommittedAt { get; set; }

        /// <summary>
        /// Ending column number (1 indexed).
        /// </summary>
        [JsonProperty("endCol", NullValueHandling = NullValueHandling.Ignore)]
        public string EndCol { get; set; }

        /// <summary>
        /// Ending line number (1 indexed).
        /// </summary>
        [JsonProperty("endLine", NullValueHandling = NullValueHandling.Ignore)]
        public string EndLine { get; set; }

        /// <summary>
        /// Path to a file.
        /// </summary>
        [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
        public string Path { get; set; }

        /// <summary>
        /// Starting column number (1 indexed).
        /// </summary>
        [JsonProperty("startCol", NullValueHandling = NullValueHandling.Ignore)]
        public string StartCol { get; set; }

        /// <summary>
        /// Starting line number (1 indexed).
        /// </summary>
        [JsonProperty("startLine", NullValueHandling = NullValueHandling.Ignore)]
        public string StartLine { get; set; }

        /// <summary>
        /// URL to code location if available, otherwise empty.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ProtosScaV1CodeLocation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CommittedAt = {(this.CommittedAt == null ? "null" : this.CommittedAt.ToString())}");
            toStringOutput.Add($"EndCol = {this.EndCol ?? "null"}");
            toStringOutput.Add($"EndLine = {this.EndLine ?? "null"}");
            toStringOutput.Add($"Path = {this.Path ?? "null"}");
            toStringOutput.Add($"StartCol = {this.StartCol ?? "null"}");
            toStringOutput.Add($"StartLine = {this.StartLine ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}