// <copyright file="Rating.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Rating.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Rating
    {
        /// <summary>
        /// RatingGood.
        /// </summary>
        [EnumMember(Value = "RATING_GOOD")]
        RatingGood,

        /// <summary>
        /// RatingBad.
        /// </summary>
        [EnumMember(Value = "RATING_BAD")]
        RatingBad
    }
}