// <copyright file="Risk.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Risk.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Risk
    {
        /// <summary>
        /// High.
        /// </summary>
        [EnumMember(Value = "high")]
        High,

        /// <summary>
        /// Low.
        /// </summary>
        [EnumMember(Value = "low")]
        Low,

        /// <summary>
        /// Neutral.
        /// </summary>
        [EnumMember(Value = "neutral")]
        Neutral
    }
}