// <copyright file="Rule.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Rule.
    /// </summary>
    public class Rule
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Rule"/> class.
        /// </summary>
        public Rule()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Rule"/> class.
        /// </summary>
        /// <param name="category">category.</param>
        /// <param name="confidence">confidence.</param>
        /// <param name="cweCategories">cweCategories.</param>
        /// <param name="hasValidators">hasValidators.</param>
        /// <param name="id">id.</param>
        /// <param name="languages">languages.</param>
        /// <param name="lastChangeAt">lastChangeAt.</param>
        /// <param name="lastChangeBy">lastChangeBy.</param>
        /// <param name="owaspCategories">owaspCategories.</param>
        /// <param name="path">path.</param>
        /// <param name="policyMode">policyMode.</param>
        /// <param name="registryMaintainer">registryMaintainer.</param>
        /// <param name="rulesets">rulesets.</param>
        /// <param name="secretType">secretType.</param>
        /// <param name="severity">severity.</param>
        /// <param name="source">source.</param>
        /// <param name="technologies">technologies.</param>
        /// <param name="url">url.</param>
        /// <param name="vulnerabilityClass">vulnerabilityClass.</param>
        public Rule(
            string category = null,
            Models.Confidence? confidence = null,
            List<string> cweCategories = null,
            bool? hasValidators = null,
            string id = null,
            List<string> languages = null,
            DateTime? lastChangeAt = null,
            string lastChangeBy = null,
            List<string> owaspCategories = null,
            string path = null,
            Models.PolicyMode? policyMode = null,
            string registryMaintainer = null,
            List<string> rulesets = null,
            string secretType = null,
            Models.Severity? severity = null,
            Models.Source? source = null,
            List<string> technologies = null,
            string url = null,
            List<string> vulnerabilityClass = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Category = category;
            this.Confidence = confidence;
            this.CweCategories = cweCategories;
            this.HasValidators = hasValidators;
            this.Id = id;
            this.Languages = languages;
            this.LastChangeAt = lastChangeAt;
            this.LastChangeBy = lastChangeBy;
            this.OwaspCategories = owaspCategories;
            this.Path = path;
            this.PolicyMode = policyMode;
            this.RegistryMaintainer = registryMaintainer;
            this.Rulesets = rulesets;
            this.SecretType = secretType;
            this.Severity = severity;
            this.Source = source;
            this.Technologies = technologies;
            this.Url = url;
            this.VulnerabilityClass = vulnerabilityClass;
        }

        /// <summary>
        /// Category the Rule is associated with.
        /// </summary>
        [JsonProperty("category", NullValueHandling = NullValueHandling.Ignore)]
        public string Category { get; set; }

        /// <summary>
        /// Confidence based on the Rule's false-positive rate.
        /// | value | description |
        /// |-------|---------------|
        /// | CONFIDENCE_HIGH |  |
        /// | CONFIDENCE_MEDIUM |  |
        /// | CONFIDENCE_LOW |  |
        /// </summary>
        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Confidence? Confidence { get; set; }

        /// <summary>
        /// The CWE associated with the Rule.
        /// </summary>
        [JsonProperty("cweCategories", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> CweCategories { get; set; }

        /// <summary>
        /// When True, the secrets rule has validators.
        /// </summary>
        [JsonProperty("hasValidators", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasValidators { get; set; }

        /// <summary>
        /// ID of the Rule.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Languages the Rule applies to.
        /// </summary>
        [JsonProperty("languages", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Languages { get; set; }

        /// <summary>
        /// Timestamp of when the Rule was last changed.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("lastChangeAt", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? LastChangeAt { get; set; }

        /// <summary>
        /// Username of who last changed the Rule.
        /// </summary>
        [JsonProperty("lastChangeBy", NullValueHandling = NullValueHandling.Ignore)]
        public string LastChangeBy { get; set; }

        /// <summary>
        /// Owasp categories the Rule is associated with.
        /// </summary>
        [JsonProperty("owaspCategories", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> OwaspCategories { get; set; }

        /// <summary>
        /// Full path of the Rule.
        /// </summary>
        [JsonProperty("path", NullValueHandling = NullValueHandling.Ignore)]
        public string Path { get; set; }

        /// <summary>
        /// Mode behavior: Monitor / Comment / Block / Disabled
        /// | value | description |
        /// |-------|---------------|
        /// | MODE_MONITOR | Monitor mode, silently report findings |
        /// | MODE_COMMENT | Comment mode, leaves PR comments but does not block |
        /// | MODE_BLOCK | Block mode, leaves PR comments and blocks PR |
        /// | MODE_DISABLED | Disabled mode, not active |
        /// </summary>
        [JsonProperty("policyMode", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PolicyMode? PolicyMode { get; set; }

        /// <summary>
        /// The Registry maintainer associated with the Rule (if applicable).
        /// </summary>
        [JsonProperty("registryMaintainer", NullValueHandling = NullValueHandling.Ignore)]
        public string RegistryMaintainer { get; set; }

        /// <summary>
        /// Rulesets to which the Rule belongs (if applicable).
        /// </summary>
        [JsonProperty("rulesets", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Rulesets { get; set; }

        /// <summary>
        /// The secret type (if applicable).
        /// </summary>
        [JsonProperty("secretType", NullValueHandling = NullValueHandling.Ignore)]
        public string SecretType { get; set; }

        /// <summary>
        /// Severity level ("seriousness" of the finding)
        /// | value | description |
        /// |-------|---------------|
        /// | SEVERITY_HIGH |  |
        /// | SEVERITY_MEDIUM |  |
        /// | SEVERITY_LOW |  |
        /// | SEVERITY_CRITICAL |  |
        /// </summary>
        [JsonProperty("severity", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Severity? Severity { get; set; }

        /// <summary>
        /// Source of the Rule
        /// | value | description |
        /// |-------|---------------|
        /// | SOURCE_PRO | From Pro rules |
        /// | SOURCE_COMMUNITY | From Semgrep Community rules |
        /// | SOURCE_CUSTOM | From Custom rules |
        /// </summary>
        [JsonProperty("source", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Source? Source { get; set; }

        /// <summary>
        /// Technologies the Rule is associated with.
        /// </summary>
        [JsonProperty("technologies", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Technologies { get; set; }

        /// <summary>
        /// The URL of the Rule.
        /// </summary>
        [JsonProperty("url", NullValueHandling = NullValueHandling.Ignore)]
        public string Url { get; set; }

        /// <summary>
        /// Vulnerability classes the Rule is associated with.
        /// </summary>
        [JsonProperty("vulnerabilityClass", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> VulnerabilityClass { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Rule : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Category = {this.Category ?? "null"}");
            toStringOutput.Add($"Confidence = {(this.Confidence == null ? "null" : this.Confidence.ToString())}");
            toStringOutput.Add($"CweCategories = {(this.CweCategories == null ? "null" : $"[{string.Join(", ", this.CweCategories)} ]")}");
            toStringOutput.Add($"HasValidators = {(this.HasValidators == null ? "null" : this.HasValidators.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Languages = {(this.Languages == null ? "null" : $"[{string.Join(", ", this.Languages)} ]")}");
            toStringOutput.Add($"LastChangeAt = {(this.LastChangeAt == null ? "null" : this.LastChangeAt.ToString())}");
            toStringOutput.Add($"LastChangeBy = {this.LastChangeBy ?? "null"}");
            toStringOutput.Add($"OwaspCategories = {(this.OwaspCategories == null ? "null" : $"[{string.Join(", ", this.OwaspCategories)} ]")}");
            toStringOutput.Add($"Path = {this.Path ?? "null"}");
            toStringOutput.Add($"PolicyMode = {(this.PolicyMode == null ? "null" : this.PolicyMode.ToString())}");
            toStringOutput.Add($"RegistryMaintainer = {this.RegistryMaintainer ?? "null"}");
            toStringOutput.Add($"Rulesets = {(this.Rulesets == null ? "null" : $"[{string.Join(", ", this.Rulesets)} ]")}");
            toStringOutput.Add($"SecretType = {this.SecretType ?? "null"}");
            toStringOutput.Add($"Severity = {(this.Severity == null ? "null" : this.Severity.ToString())}");
            toStringOutput.Add($"Source = {(this.Source == null ? "null" : this.Source.ToString())}");
            toStringOutput.Add($"Technologies = {(this.Technologies == null ? "null" : $"[{string.Join(", ", this.Technologies)} ]")}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"VulnerabilityClass = {(this.VulnerabilityClass == null ? "null" : $"[{string.Join(", ", this.VulnerabilityClass)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}