// <copyright file="SastFinding.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// SastFinding.
    /// </summary>
    public class SastFinding
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SastFinding"/> class.
        /// </summary>
        public SastFinding()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SastFinding"/> class.
        /// </summary>
        /// <param name="assistant">assistant.</param>
        /// <param name="categories">categories.</param>
        /// <param name="clickToFixFailures">click_to_fix_failures.</param>
        /// <param name="clickToFixPrs">click_to_fix_prs.</param>
        /// <param name="confidence">confidence.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="externalTicket">external_ticket.</param>
        /// <param name="firstSeenScanId">first_seen_scan_id.</param>
        /// <param name="id">id.</param>
        /// <param name="lineOfCodeUrl">line_of_code_url.</param>
        /// <param name="location">location.</param>
        /// <param name="matchBasedId">match_based_id.</param>
        /// <param name="mRef">ref.</param>
        /// <param name="relevantSince">relevant_since.</param>
        /// <param name="repository">repository.</param>
        /// <param name="reviewComments">review_comments.</param>
        /// <param name="rule">rule.</param>
        /// <param name="ruleMessage">rule_message.</param>
        /// <param name="ruleName">rule_name.</param>
        /// <param name="severity">severity.</param>
        /// <param name="sourcingPolicy">sourcing_policy.</param>
        /// <param name="state">state.</param>
        /// <param name="stateUpdatedAt">state_updated_at.</param>
        /// <param name="status">status.</param>
        /// <param name="syntacticId">syntactic_id.</param>
        /// <param name="triageComment">triage_comment.</param>
        /// <param name="triageReason">triage_reason.</param>
        /// <param name="triageState">triage_state.</param>
        /// <param name="triagedAt">triaged_at.</param>
        public SastFinding(
            Models.Assistant assistant = null,
            List<string> categories = null,
            List<Models.ClickToFixFailure> clickToFixFailures = null,
            List<Models.ClickToFixPr> clickToFixPrs = null,
            Models.Confidence1? confidence = null,
            string createdAt = null,
            Models.ExternalTicket externalTicket = null,
            long? firstSeenScanId = null,
            long? id = null,
            string lineOfCodeUrl = null,
            Models.FindingLocation location = null,
            string matchBasedId = null,
            string mRef = null,
            string relevantSince = null,
            Models.FindingRepository repository = null,
            List<Models.ReviewComment> reviewComments = null,
            Models.FindingRule rule = null,
            string ruleMessage = null,
            string ruleName = null,
            Models.Severity1? severity = null,
            Models.PolicyReference sourcingPolicy = null,
            Models.State? state = null,
            string stateUpdatedAt = null,
            Models.Status? status = null,
            string syntacticId = null,
            string triageComment = null,
            Models.TriageReason? triageReason = null,
            Models.TriageState? triageState = null,
            string triagedAt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Assistant = assistant;
            this.Categories = categories;
            this.ClickToFixFailures = clickToFixFailures;
            this.ClickToFixPrs = clickToFixPrs;
            this.Confidence = confidence;
            this.CreatedAt = createdAt;
            this.ExternalTicket = externalTicket;
            this.FirstSeenScanId = firstSeenScanId;
            this.Id = id;
            this.LineOfCodeUrl = lineOfCodeUrl;
            this.Location = location;
            this.MatchBasedId = matchBasedId;
            this.MRef = mRef;
            this.RelevantSince = relevantSince;
            this.Repository = repository;
            this.ReviewComments = reviewComments;
            this.Rule = rule;
            this.RuleMessage = ruleMessage;
            this.RuleName = ruleName;
            this.Severity = severity;
            this.SourcingPolicy = sourcingPolicy;
            this.State = state;
            this.StateUpdatedAt = stateUpdatedAt;
            this.Status = status;
            this.SyntacticId = syntacticId;
            this.TriageComment = triageComment;
            this.TriageReason = triageReason;
            this.TriageState = triageState;
            this.TriagedAt = triagedAt;
        }

        /// <summary>
        /// Semgrep Assistant data. Only present if Assistant is enabled
        /// </summary>
        [JsonProperty("assistant", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Assistant Assistant { get; set; }

        /// <summary>
        /// The categories of the finding as classified by the associated rule metadata
        /// </summary>
        [JsonConverter(typeof(CoreListConverter), typeof(JsonStringConverter))]
        [JsonProperty("categories", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Categories { get; set; }

        /// <summary>
        /// Failed PR creation attempts by Semgrep's autofix feature (Click to Fix) for this finding
        /// </summary>
        [JsonProperty("click_to_fix_failures", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickToFixFailure> ClickToFixFailures { get; set; }

        /// <summary>
        /// Pull requests created by Semgrep's autofix feature (Click to Fix) for this finding
        /// </summary>
        [JsonProperty("click_to_fix_prs", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ClickToFixPr> ClickToFixPrs { get; set; }

        /// <summary>
        /// Confidence of the finding, derived from the rule that triggered it
        /// </summary>
        [JsonProperty("confidence", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Confidence1? Confidence { get; set; }

        /// <summary>
        /// The timestamp when this finding was created
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("created_at", NullValueHandling = NullValueHandling.Ignore)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// External ticket associated with finding
        /// </summary>
        [JsonProperty("external_ticket", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ExternalTicket ExternalTicket { get; set; }

        /// <summary>
        /// Unique ID of the Semgrep scan that first identified this finding
        /// </summary>
        [JsonProperty("first_seen_scan_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? FirstSeenScanId { get; set; }

        /// <summary>
        /// Unique ID of this finding
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        /// <summary>
        /// The source URL including file and line number
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("line_of_code_url", NullValueHandling = NullValueHandling.Ignore)]
        public string LineOfCodeUrl { get; set; }

        /// <summary>
        /// Location of the record in a file, as reported by Semgrep. If null, then the information does not exist or lacks integrity (older or broken scans)
        /// </summary>
        [JsonProperty("location", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FindingLocation Location { get; set; }

        /// <summary>
        /// ID calculated based on a finding's file path, rule identifier and pattern, and index
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("match_based_id", NullValueHandling = NullValueHandling.Ignore)]
        public string MatchBasedId { get; set; }

        /// <summary>
        /// External reference to the source of this finding (e.g. PR)
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("ref", NullValueHandling = NullValueHandling.Ignore)]
        public string MRef { get; set; }

        /// <summary>
        /// The timestamp when this finding was detected by Semgrep (the first time, or when reintroduced)
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("relevant_since", NullValueHandling = NullValueHandling.Ignore)]
        public string RelevantSince { get; set; }

        /// <summary>
        /// Which repository this finding was identified in
        /// </summary>
        [JsonProperty("repository", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FindingRepository Repository { get; set; }

        /// <summary>
        /// List of external review comment information associated with a finding
        /// </summary>
        [JsonProperty("review_comments", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ReviewComment> ReviewComments { get; set; }

        /// <summary>
        /// Rule that applies to this finding
        /// </summary>
        [JsonProperty("rule", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FindingRule Rule { get; set; }

        /// <summary>
        /// Deprecated in favor of rule.message. Rule message at the time of finding identification. Older findings may not have a value for this field
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("rule_message", NullValueHandling = NullValueHandling.Ignore)]
        public string RuleMessage { get; set; }

        /// <summary>
        /// Deprecated in favor of rule.name
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("rule_name", NullValueHandling = NullValueHandling.Ignore)]
        public string RuleName { get; set; }

        /// <summary>
        /// Severity of the finding, derived from the rule that triggered it. Low is equivalent to INFO, Medium to WARNING, and High to ERROR
        /// </summary>
        [JsonProperty("severity", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Severity1? Severity { get; set; }

        /// <summary>
        /// Reference to a policy, with some basic information. If null, then the information does not exist or lacks integrity (older or broken scans)
        /// </summary>
        [JsonProperty("sourcing_policy", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PolicyReference SourcingPolicy { get; set; }

        /// <summary>
        /// The finding's resolution state. Managed only by changes detected at scan time, the `state` is combined with `triage_state` to ultimately determine a final `status` which is exposed in the UI and API
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.State? State { get; set; }

        /// <summary>
        /// When this issue's `state` (resolution state) was last updated, as distinct from when the issue was triaged (`triaged_at`)
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("state_updated_at", NullValueHandling = NullValueHandling.Ignore)]
        public string StateUpdatedAt { get; set; }

        /// <summary>
        /// The finding's status as exposed in the UI. Status is a derived property combining information from the finding `state` and `triage_state`. The `triage_state` can be used to override the scan state if the finding is still detected
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Status? Status { get; set; }

        /// <summary>
        /// ID calculated based on a finding's file path, rule identifier and matched code, and index. Prefer `match_based_id`
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("syntactic_id", NullValueHandling = NullValueHandling.Ignore)]
        public string SyntacticId { get; set; }

        /// <summary>
        /// The detailed comment provided during triage
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("triage_comment", NullValueHandling = NullValueHandling.Ignore)]
        public string TriageComment { get; set; }

        /// <summary>
        /// Reason provided when this issue was triaged
        /// </summary>
        [JsonProperty("triage_reason", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TriageReason? TriageReason { get; set; }

        /// <summary>
        /// The finding's triage state. Note: "reviewing" and "fixing" are only in private beta. Set by the user and used along with state to generate the final "status" viewable in the UI
        /// </summary>
        [JsonProperty("triage_state", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TriageState? TriageState { get; set; }

        /// <summary>
        /// When the finding was triaged
        /// </summary>
        [JsonConverter(typeof(JsonStringConverter))]
        [JsonProperty("triaged_at", NullValueHandling = NullValueHandling.Ignore)]
        public string TriagedAt { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SastFinding : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Assistant = {(this.Assistant == null ? "null" : this.Assistant.ToString())}");
            toStringOutput.Add($"Categories = {(this.Categories == null ? "null" : $"[{string.Join(", ", this.Categories)} ]")}");
            toStringOutput.Add($"ClickToFixFailures = {(this.ClickToFixFailures == null ? "null" : $"[{string.Join(", ", this.ClickToFixFailures)} ]")}");
            toStringOutput.Add($"ClickToFixPrs = {(this.ClickToFixPrs == null ? "null" : $"[{string.Join(", ", this.ClickToFixPrs)} ]")}");
            toStringOutput.Add($"Confidence = {(this.Confidence == null ? "null" : this.Confidence.ToString())}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt ?? "null"}");
            toStringOutput.Add($"ExternalTicket = {(this.ExternalTicket == null ? "null" : this.ExternalTicket.ToString())}");
            toStringOutput.Add($"FirstSeenScanId = {(this.FirstSeenScanId == null ? "null" : this.FirstSeenScanId.ToString())}");
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"LineOfCodeUrl = {this.LineOfCodeUrl ?? "null"}");
            toStringOutput.Add($"Location = {(this.Location == null ? "null" : this.Location.ToString())}");
            toStringOutput.Add($"MatchBasedId = {this.MatchBasedId ?? "null"}");
            toStringOutput.Add($"MRef = {this.MRef ?? "null"}");
            toStringOutput.Add($"RelevantSince = {this.RelevantSince ?? "null"}");
            toStringOutput.Add($"Repository = {(this.Repository == null ? "null" : this.Repository.ToString())}");
            toStringOutput.Add($"ReviewComments = {(this.ReviewComments == null ? "null" : $"[{string.Join(", ", this.ReviewComments)} ]")}");
            toStringOutput.Add($"Rule = {(this.Rule == null ? "null" : this.Rule.ToString())}");
            toStringOutput.Add($"RuleMessage = {this.RuleMessage ?? "null"}");
            toStringOutput.Add($"RuleName = {this.RuleName ?? "null"}");
            toStringOutput.Add($"Severity = {(this.Severity == null ? "null" : this.Severity.ToString())}");
            toStringOutput.Add($"SourcingPolicy = {(this.SourcingPolicy == null ? "null" : this.SourcingPolicy.ToString())}");
            toStringOutput.Add($"State = {(this.State == null ? "null" : this.State.ToString())}");
            toStringOutput.Add($"StateUpdatedAt = {this.StateUpdatedAt ?? "null"}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"SyntacticId = {this.SyntacticId ?? "null"}");
            toStringOutput.Add($"TriageComment = {this.TriageComment ?? "null"}");
            toStringOutput.Add($"TriageReason = {(this.TriageReason == null ? "null" : this.TriageReason.ToString())}");
            toStringOutput.Add($"TriageState = {(this.TriageState == null ? "null" : this.TriageState.ToString())}");
            toStringOutput.Add($"TriagedAt = {this.TriagedAt ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}