// <copyright file="SbomOutputFormat.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// SbomOutputFormat.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum SbomOutputFormat
    {
        /// <summary>
        /// SbomOutputFormatJson.
        /// </summary>
        [EnumMember(Value = "SBOM_OUTPUT_FORMAT_JSON")]
        SbomOutputFormatJson,

        /// <summary>
        /// SbomOutputFormatCyclonedx.
        /// </summary>
        [EnumMember(Value = "SBOM_OUTPUT_FORMAT_CYCLONEDX")]
        SbomOutputFormatCyclonedx
    }
}