// <copyright file="ScmType.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ScmType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ScmType
    {
        /// <summary>
        /// ScmTypeGithub.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_GITHUB")]
        ScmTypeGithub,

        /// <summary>
        /// ScmTypeGithubEnterprise.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_GITHUB_ENTERPRISE")]
        ScmTypeGithubEnterprise,

        /// <summary>
        /// ScmTypeGitlab.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_GITLAB")]
        ScmTypeGitlab,

        /// <summary>
        /// ScmTypeGitlabSelfmanaged.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_GITLAB_SELFMANAGED")]
        ScmTypeGitlabSelfmanaged,

        /// <summary>
        /// ScmTypeBitbucket.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_BITBUCKET")]
        ScmTypeBitbucket,

        /// <summary>
        /// ScmTypeBitbucketDatacenter.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_BITBUCKET_DATACENTER")]
        ScmTypeBitbucketDatacenter,

        /// <summary>
        /// ScmTypeAzureDevops.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_AZURE_DEVOPS")]
        ScmTypeAzureDevops,

        /// <summary>
        /// ScmTypeUnknown.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_UNKNOWN")]
        ScmTypeUnknown,

        /// <summary>
        /// ScmTypeHarness.
        /// </summary>
        [EnumMember(Value = "SCM_TYPE_HARNESS")]
        ScmTypeHarness
    }
}