// <copyright file="SearchScansRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// SearchScansRequest.
    /// </summary>
    public class SearchScansRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchScansRequest"/> class.
        /// </summary>
        public SearchScansRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchScansRequest"/> class.
        /// </summary>
        /// <param name="deploymentId">deploymentId.</param>
        /// <param name="branch">branch.</param>
        /// <param name="cursor">cursor.</param>
        /// <param name="isFullScan">is_full_scan.</param>
        /// <param name="limit">limit.</param>
        /// <param name="products">products.</param>
        /// <param name="repositoryId">repository_id.</param>
        /// <param name="since">since.</param>
        /// <param name="statuses">statuses.</param>
        /// <param name="totalTime">total_time.</param>
        public SearchScansRequest(
            string deploymentId,
            string branch = null,
            string cursor = null,
            int? isFullScan = null,
            int? limit = null,
            Models.Products? products = null,
            int? repositoryId = null,
            DateTime? since = null,
            Models.Statuses? statuses = null,
            Models.FloatRange totalTime = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Branch = branch;
            this.Cursor = cursor;
            this.DeploymentId = deploymentId;
            this.IsFullScan = isFullScan;
            this.Limit = limit;
            this.Products = products;
            this.RepositoryId = repositoryId;
            this.Since = since;
            this.Statuses = statuses;
            this.TotalTime = totalTime;
        }

        /// <summary>
        /// Only get scans from the specified branch
        /// </summary>
        [JsonProperty("branch", NullValueHandling = NullValueHandling.Ignore)]
        public string Branch { get; set; }

        /// <summary>
        /// Cursor to paginate through the results
        /// </summary>
        [JsonProperty("cursor", NullValueHandling = NullValueHandling.Ignore)]
        public string Cursor { get; set; }

        /// <summary>
        /// Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// Only get scans that are full scans (if false, only get diff scans)
        /// </summary>
        [JsonProperty("is_full_scan", NullValueHandling = NullValueHandling.Ignore)]
        public int? IsFullScan { get; set; }

        /// <summary>
        /// Page size to paginate through the results (default is 100, max is 500)
        /// </summary>
        [JsonProperty("limit", NullValueHandling = NullValueHandling.Ignore)]
        public int? Limit { get; set; }

        /// <summary>
        /// Only get scans that have these enabled products
        /// | value | description |
        /// |-------|---------------|
        /// | PRODUCT_SAST |  |
        /// | PRODUCT_SCA |  |
        /// | PRODUCT_SECRETS |  |
        /// | PRODUCT_AI_SAST |  |
        /// </summary>
        [JsonProperty("products", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Products? Products { get; set; }

        /// <summary>
        /// Only get scans for this repo
        /// </summary>
        [JsonProperty("repository_id", NullValueHandling = NullValueHandling.Ignore)]
        public int? RepositoryId { get; set; }

        /// <summary>
        /// Only get scans created after this time. Provide time in ISO 8601 format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("since", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? Since { get; set; }

        /// <summary>
        /// Only get scans that have one of these statuses
        /// | value | description |
        /// |-------|---------------|
        /// | SCAN_STATUS_RUNNING | The scan is currently running |
        /// | SCAN_STATUS_COMPLETED | The scan has completed successfully (0 or 1 exit code) |
        /// | SCAN_STATUS_PENDING | The scan is queued and waiting to start |
        /// | SCAN_STATUS_CANCELLED | The scan was cancelled before completion |
        /// | SCAN_STATUS_ERROR | The scan has exited with a failure (exit code not 0 or 1) |
        /// | SCAN_STATUS_NEVER_FINISHED | The scan did not report an error or success after over an hour |
        /// </summary>
        [JsonProperty("statuses", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Statuses? Statuses { get; set; }

        /// <summary>
        /// Gets or sets TotalTime.
        /// </summary>
        [JsonProperty("total_time", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FloatRange TotalTime { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SearchScansRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Branch = {this.Branch ?? "null"}");
            toStringOutput.Add($"Cursor = {this.Cursor ?? "null"}");
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"IsFullScan = {(this.IsFullScan == null ? "null" : this.IsFullScan.ToString())}");
            toStringOutput.Add($"Limit = {(this.Limit == null ? "null" : this.Limit.ToString())}");
            toStringOutput.Add($"Products = {(this.Products == null ? "null" : this.Products.ToString())}");
            toStringOutput.Add($"RepositoryId = {(this.RepositoryId == null ? "null" : this.RepositoryId.ToString())}");
            toStringOutput.Add($"Since = {(this.Since == null ? "null" : this.Since.ToString())}");
            toStringOutput.Add($"Statuses = {(this.Statuses == null ? "null" : this.Statuses.ToString())}");
            toStringOutput.Add($"TotalTime = {(this.TotalTime == null ? "null" : this.TotalTime.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}