// <copyright file="Severity4.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Severity4.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Severity4
    {
        /// <summary>
        /// SeverityHigh.
        /// </summary>
        [EnumMember(Value = "SEVERITY_HIGH")]
        SeverityHigh,

        /// <summary>
        /// SeverityMedium.
        /// </summary>
        [EnumMember(Value = "SEVERITY_MEDIUM")]
        SeverityMedium,

        /// <summary>
        /// SeverityLow.
        /// </summary>
        [EnumMember(Value = "SEVERITY_LOW")]
        SeverityLow,

        /// <summary>
        /// SeverityCritical.
        /// </summary>
        [EnumMember(Value = "SEVERITY_CRITICAL")]
        SeverityCritical
    }
}