// <copyright file="Source.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Source.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Source
    {
        /// <summary>
        /// SourcePro.
        /// </summary>
        [EnumMember(Value = "SOURCE_PRO")]
        SourcePro,

        /// <summary>
        /// SourceCommunity.
        /// </summary>
        [EnumMember(Value = "SOURCE_COMMUNITY")]
        SourceCommunity,

        /// <summary>
        /// SourceCustom.
        /// </summary>
        [EnumMember(Value = "SOURCE_CUSTOM")]
        SourceCustom
    }
}