// <copyright file="Status6.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Status6.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status6
    {
        /// <summary>
        /// FindingStatusOpen.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_OPEN")]
        FindingStatusOpen,

        /// <summary>
        /// FindingStatusIgnored.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_IGNORED")]
        FindingStatusIgnored,

        /// <summary>
        /// FindingStatusFixed.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_FIXED")]
        FindingStatusFixed,

        /// <summary>
        /// FindingStatusRemoved.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_REMOVED")]
        FindingStatusRemoved,

        /// <summary>
        /// FindingStatusUnknown.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_UNKNOWN")]
        FindingStatusUnknown,

        /// <summary>
        /// FindingStatusProvisionallyIgnored.
        /// </summary>
        [EnumMember(Value = "FINDING_STATUS_PROVISIONALLY_IGNORED")]
        FindingStatusProvisionallyIgnored
    }
}