// <copyright file="Status7.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Status7.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status7
    {
        /// <summary>
        /// ScanStatusRunning.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_RUNNING")]
        ScanStatusRunning,

        /// <summary>
        /// ScanStatusCompleted.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_COMPLETED")]
        ScanStatusCompleted,

        /// <summary>
        /// ScanStatusPending.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_PENDING")]
        ScanStatusPending,

        /// <summary>
        /// ScanStatusCancelled.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_CANCELLED")]
        ScanStatusCancelled,

        /// <summary>
        /// ScanStatusError.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_ERROR")]
        ScanStatusError,

        /// <summary>
        /// ScanStatusNeverFinished.
        /// </summary>
        [EnumMember(Value = "SCAN_STATUS_NEVER_FINISHED")]
        ScanStatusNeverFinished
    }
}