// <copyright file="State.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// State.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum State
    {
        /// <summary>
        /// Fixed.
        /// </summary>
        [EnumMember(Value = "fixed")]
        Fixed,

        /// <summary>
        /// Muted.
        /// </summary>
        [EnumMember(Value = "muted")]
        Muted,

        /// <summary>
        /// Unresolved.
        /// </summary>
        [EnumMember(Value = "unresolved")]
        Unresolved
    }
}