// <copyright file="Status3.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Status3.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status3
    {
        /// <summary>
        /// SbomExportStatusInProgress.
        /// </summary>
        [EnumMember(Value = "SBOM_EXPORT_STATUS_IN_PROGRESS")]
        SbomExportStatusInProgress,

        /// <summary>
        /// SbomExportStatusCompleted.
        /// </summary>
        [EnumMember(Value = "SBOM_EXPORT_STATUS_COMPLETED")]
        SbomExportStatusCompleted,

        /// <summary>
        /// SbomExportStatusFailed.
        /// </summary>
        [EnumMember(Value = "SBOM_EXPORT_STATUS_FAILED")]
        SbomExportStatusFailed
    }
}