// <copyright file="Status.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Status.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status
    {
        /// <summary>
        /// Open.
        /// </summary>
        [EnumMember(Value = "open")]
        Open,

        /// <summary>
        /// Fixed.
        /// </summary>
        [EnumMember(Value = "fixed")]
        Fixed,

        /// <summary>
        /// Ignored.
        /// </summary>
        [EnumMember(Value = "ignored")]
        Ignored,

        /// <summary>
        /// Reviewing.
        /// </summary>
        [EnumMember(Value = "reviewing")]
        Reviewing,

        /// <summary>
        /// Fixing.
        /// </summary>
        [EnumMember(Value = "fixing")]
        Fixing,

        /// <summary>
        /// ProvisionallyIgnored.
        /// </summary>
        [EnumMember(Value = "provisionally_ignored")]
        ProvisionallyIgnored
    }
}