// <copyright file="ToggleProjectManagedScanRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ToggleProjectManagedScanRequest.
    /// </summary>
    public class ToggleProjectManagedScanRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToggleProjectManagedScanRequest"/> class.
        /// </summary>
        public ToggleProjectManagedScanRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ToggleProjectManagedScanRequest"/> class.
        /// </summary>
        /// <param name="deploymentSlug">deploymentSlug.</param>
        /// <param name="projectName">projectName.</param>
        /// <param name="diffScan">diff_scan.</param>
        /// <param name="fullScan">full_scan.</param>
        public ToggleProjectManagedScanRequest(
            string deploymentSlug,
            string projectName,
            Models.ProtosOpenapiV1DiffScan diffScan = null,
            Models.ProtosOpenapiV1FullScan fullScan = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DeploymentSlug = deploymentSlug;
            this.DiffScan = diffScan;
            this.FullScan = fullScan;
            this.ProjectName = projectName;
        }

        /// <summary>
        /// Slug of the deployment name. Can be found at `/deployments`, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentSlug")]
        public string DeploymentSlug { get; set; }

        /// <summary>
        /// Gets or sets DiffScan.
        /// </summary>
        [JsonProperty("diff_scan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosOpenapiV1DiffScan DiffScan { get; set; }

        /// <summary>
        /// Gets or sets FullScan.
        /// </summary>
        [JsonProperty("full_scan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ProtosOpenapiV1FullScan FullScan { get; set; }

        /// <summary>
        /// Name of the project, typically the repository formatted as a path.
        /// </summary>
        [JsonProperty("projectName")]
        public string ProjectName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ToggleProjectManagedScanRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeploymentSlug = {this.DeploymentSlug ?? "null"}");
            toStringOutput.Add($"DiffScan = {(this.DiffScan == null ? "null" : this.DiffScan.ToString())}");
            toStringOutput.Add($"FullScan = {(this.FullScan == null ? "null" : this.FullScan.ToString())}");
            toStringOutput.Add($"ProjectName = {this.ProjectName ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}