// <copyright file="Transitivity.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Transitivity.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Transitivity
    {
        /// <summary>
        /// UnknownTransitivity.
        /// </summary>
        [EnumMember(Value = "UNKNOWN_TRANSITIVITY")]
        UnknownTransitivity,

        /// <summary>
        /// Transitive.
        /// </summary>
        [EnumMember(Value = "TRANSITIVE")]
        Transitive,

        /// <summary>
        /// Direct.
        /// </summary>
        [EnumMember(Value = "DIRECT")]
        Direct
    }
}