// <copyright file="Transitivities.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Transitivities.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Transitivities
    {
        /// <summary>
        /// Direct.
        /// </summary>
        [EnumMember(Value = "direct")]
        Direct,

        /// <summary>
        /// Transitive.
        /// </summary>
        [EnumMember(Value = "transitive")]
        Transitive,

        /// <summary>
        /// Unknown.
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown
    }
}