// <copyright file="TriageReasons2.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// TriageReasons2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TriageReasons2
    {
        /// <summary>
        /// AcceptableRisk.
        /// </summary>
        [EnumMember(Value = "acceptable_risk")]
        AcceptableRisk,

        /// <summary>
        /// FalsePositive.
        /// </summary>
        [EnumMember(Value = "false_positive")]
        FalsePositive,

        /// <summary>
        /// NoTime.
        /// </summary>
        [EnumMember(Value = "no_time")]
        NoTime,

        /// <summary>
        /// NoTriageReason.
        /// </summary>
        [EnumMember(Value = "no_triage_reason")]
        NoTriageReason,

        /// <summary>
        /// Duplicate.
        /// </summary>
        [EnumMember(Value = "duplicate")]
        Duplicate
    }
}