// <copyright file="TriageState.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// TriageState.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TriageState
    {
        /// <summary>
        /// Untriaged.
        /// </summary>
        [EnumMember(Value = "untriaged")]
        Untriaged,

        /// <summary>
        /// Ignored.
        /// </summary>
        [EnumMember(Value = "ignored")]
        Ignored,

        /// <summary>
        /// Reopened.
        /// </summary>
        [EnumMember(Value = "reopened")]
        Reopened,

        /// <summary>
        /// Reviewing.
        /// </summary>
        [EnumMember(Value = "reviewing")]
        Reviewing,

        /// <summary>
        /// Fixing.
        /// </summary>
        [EnumMember(Value = "fixing")]
        Fixing,

        /// <summary>
        /// ProvisionallyIgnored.
        /// </summary>
        [EnumMember(Value = "provisionally_ignored")]
        ProvisionallyIgnored
    }
}