// <copyright file="UnlinkTicketRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// UnlinkTicketRequest.
    /// </summary>
    public class UnlinkTicketRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnlinkTicketRequest"/> class.
        /// </summary>
        public UnlinkTicketRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UnlinkTicketRequest"/> class.
        /// </summary>
        /// <param name="deploymentId">deploymentId.</param>
        /// <param name="issueIds">issue_ids.</param>
        public UnlinkTicketRequest(
            string deploymentId,
            List<string> issueIds)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DeploymentId = deploymentId;
            this.IssueIds = issueIds;
        }

        /// <summary>
        /// Deployment ID. Can be found at /deployments, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// An array of Semgrep finding IDs to unlink tickets from.
        /// </summary>
        [JsonProperty("issue_ids")]
        public List<string> IssueIds { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UnlinkTicketRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"IssueIds = {(this.IssueIds == null ? "null" : $"[{string.Join(", ", this.IssueIds)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}