// <copyright file="UpdatePolicyRequest.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SemgrepWebApp.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// UpdatePolicyRequest.
    /// </summary>
    public class UpdatePolicyRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePolicyRequest"/> class.
        /// </summary>
        public UpdatePolicyRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePolicyRequest"/> class.
        /// </summary>
        /// <param name="deploymentId">deploymentId.</param>
        /// <param name="policyId">policyId.</param>
        /// <param name="policyMode">policyMode.</param>
        /// <param name="rulePath">rulePath.</param>
        public UpdatePolicyRequest(
            string deploymentId,
            string policyId,
            Models.PolicyMode3 policyMode,
            string rulePath)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DeploymentId = deploymentId;
            this.PolicyId = policyId;
            this.PolicyMode = policyMode;
            this.RulePath = rulePath;
        }

        /// <summary>
        /// Deployment ID (numeric). Example: `123`. Can be found at `/deployments`, or in your Settings in the web UI.
        /// </summary>
        [JsonProperty("deploymentId")]
        public string DeploymentId { get; set; }

        /// <summary>
        /// Policy ID (numeric). Example: `456`. Can be found at `/deployments/{deploymentId}/policies`.
        /// </summary>
        [JsonProperty("policyId")]
        public string PolicyId { get; set; }

        /// <summary>
        /// New policy mode to set for the Rule.
        ///  - MODE_MONITOR: Monitor mode, silently report findings
        ///  - MODE_COMMENT: Comment mode, leaves PR comments but does not block
        ///  - MODE_BLOCK: Block mode, leaves PR comments and blocks PR
        ///  - MODE_DISABLED: Disabled mode, not active
        /// | value | description |
        /// |-------|---------------|
        /// | MODE_MONITOR | Monitor mode, silently report findings |
        /// | MODE_COMMENT | Comment mode, leaves PR comments but does not block |
        /// | MODE_BLOCK | Block mode, leaves PR comments and blocks PR |
        /// | MODE_DISABLED | Disabled mode, not active |
        /// </summary>
        [JsonProperty("policyMode")]
        public Models.PolicyMode3 PolicyMode { get; set; }

        /// <summary>
        /// Full path of the Rule.
        /// </summary>
        [JsonProperty("rulePath")]
        public string RulePath { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"UpdatePolicyRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DeploymentId = {this.DeploymentId ?? "null"}");
            toStringOutput.Add($"PolicyId = {this.PolicyId ?? "null"}");
            toStringOutput.Add($"PolicyMode = {this.PolicyMode}");
            toStringOutput.Add($"RulePath = {this.RulePath ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}