// <copyright file="ValidationState2.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ValidationState2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValidationState2
    {
        /// <summary>
        /// ValidationStateConfirmedValid.
        /// </summary>
        [EnumMember(Value = "VALIDATION_STATE_CONFIRMED_VALID")]
        ValidationStateConfirmedValid,

        /// <summary>
        /// ValidationStateConfirmedInvalid.
        /// </summary>
        [EnumMember(Value = "VALIDATION_STATE_CONFIRMED_INVALID")]
        ValidationStateConfirmedInvalid,

        /// <summary>
        /// ValidationStateValidationError.
        /// </summary>
        [EnumMember(Value = "VALIDATION_STATE_VALIDATION_ERROR")]
        ValidationStateValidationError,

        /// <summary>
        /// ValidationStateNoValidator.
        /// </summary>
        [EnumMember(Value = "VALIDATION_STATE_NO_VALIDATOR")]
        ValidationStateNoValidator
    }
}