// <copyright file="ValidationState.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// ValidationState.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ValidationState
    {
        /// <summary>
        /// ConfirmedValid.
        /// </summary>
        [EnumMember(Value = "confirmed_valid")]
        ConfirmedValid,

        /// <summary>
        /// ConfirmedInvalid.
        /// </summary>
        [EnumMember(Value = "confirmed_invalid")]
        ConfirmedInvalid,

        /// <summary>
        /// ValidationError.
        /// </summary>
        [EnumMember(Value = "validation_error")]
        ValidationError,

        /// <summary>
        /// NoValidator.
        /// </summary>
        [EnumMember(Value = "no_validator")]
        NoValidator
    }
}