// <copyright file="Verdict.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Verdict.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Verdict
    {
        /// <summary>
        /// VerdictTruePositive.
        /// </summary>
        [EnumMember(Value = "VERDICT_TRUE_POSITIVE")]
        VerdictTruePositive,

        /// <summary>
        /// VerdictFalsePositive.
        /// </summary>
        [EnumMember(Value = "VERDICT_FALSE_POSITIVE")]
        VerdictFalsePositive,

        /// <summary>
        /// VerdictNoVerdict.
        /// </summary>
        [EnumMember(Value = "VERDICT_NO_VERDICT")]
        VerdictNoVerdict
    }
}