// <copyright file="Visibility.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SemgrepWebApp.Standard.Models
{
    /// <summary>
    /// Visibility.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Visibility
    {
        /// <summary>
        /// RepositoryVisibilityPublic.
        /// </summary>
        [EnumMember(Value = "REPOSITORY_VISIBILITY_PUBLIC")]
        RepositoryVisibilityPublic,

        /// <summary>
        /// RepositoryVisibilityPrivate.
        /// </summary>
        [EnumMember(Value = "REPOSITORY_VISIBILITY_PRIVATE")]
        RepositoryVisibilityPrivate,

        /// <summary>
        /// RepositoryVisibilityUnknown.
        /// </summary>
        [EnumMember(Value = "REPOSITORY_VISIBILITY_UNKNOWN")]
        RepositoryVisibilityUnknown
    }
}