// <copyright file="SemgrepWebAppClient.cs" company="APIMatic">
// SemgrepWebApp.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using SemgrepWebApp.Standard.Apis;
using SemgrepWebApp.Standard.Authentication;
using SemgrepWebApp.Standard.Http.Client;
using SemgrepWebApp.Standard.Logging;
using System;
using System.Collections.Generic;

namespace SemgrepWebApp.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Api and holds the
    /// configuration of the SDK.
    /// </summary>
    public sealed class SemgrepWebAppClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Semgrep, "https://semgrep.dev" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet-SDK/0.0.1 (OS: {os-info}, Engine: {engine}/{engine-version})";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<DeploymentsServiceApi> deploymentsService;
        private readonly Lazy<FindingsServiceApi> findingsService;
        private readonly Lazy<MiscServiceApi> miscService;
        private readonly Lazy<PoliciesServiceApi> policiesService;
        private readonly Lazy<ProjectsServiceApi> projectsService;
        private readonly Lazy<ScansServiceApi> scansService;
        private readonly Lazy<SecretsServiceApi> secretsService;
        private readonly Lazy<SupplyChainServiceApi> supplyChainService;
        private readonly Lazy<TicketingServiceApi> ticketingService;
        private readonly Lazy<TriageServiceApi> triageService;

        private SemgrepWebAppClient(
            Environment environment,
            SemgrepAdminJwtModel semgrepAdminJwtModel,
            SemgrepJwtModel semgrepJwtModel,
            SemgrepWebTokenModel semgrepWebTokenModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            SemgrepAdminJwtModel = semgrepAdminJwtModel;
            var semgrepAdminJwtManager = new SemgrepAdminJwtManager(semgrepAdminJwtModel);
            SemgrepJwtModel = semgrepJwtModel;
            var semgrepJwtManager = new SemgrepJwtManager(semgrepJwtModel);
            SemgrepWebTokenModel = semgrepWebTokenModel;
            var semgrepWebTokenManager = new SemgrepWebTokenManager(semgrepWebTokenModel);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"SemgrepAdminJWT", semgrepAdminJwtManager},
                    {"SemgrepJWT", semgrepJwtManager},
                    {"SemgrepWebToken", semgrepWebTokenManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Semgrep)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            SemgrepAdminJwtCredentials = semgrepAdminJwtManager;
            SemgrepJwtCredentials = semgrepJwtManager;
            SemgrepWebTokenCredentials = semgrepWebTokenManager;

            this.deploymentsService = new Lazy<DeploymentsServiceApi>(
                () => new DeploymentsServiceApi(globalConfiguration));
            this.findingsService = new Lazy<FindingsServiceApi>(
                () => new FindingsServiceApi(globalConfiguration));
            this.miscService = new Lazy<MiscServiceApi>(
                () => new MiscServiceApi(globalConfiguration));
            this.policiesService = new Lazy<PoliciesServiceApi>(
                () => new PoliciesServiceApi(globalConfiguration));
            this.projectsService = new Lazy<ProjectsServiceApi>(
                () => new ProjectsServiceApi(globalConfiguration));
            this.scansService = new Lazy<ScansServiceApi>(
                () => new ScansServiceApi(globalConfiguration));
            this.secretsService = new Lazy<SecretsServiceApi>(
                () => new SecretsServiceApi(globalConfiguration));
            this.supplyChainService = new Lazy<SupplyChainServiceApi>(
                () => new SupplyChainServiceApi(globalConfiguration));
            this.ticketingService = new Lazy<TicketingServiceApi>(
                () => new TicketingServiceApi(globalConfiguration));
            this.triageService = new Lazy<TriageServiceApi>(
                () => new TriageServiceApi(globalConfiguration));
        }

        /// <summary>
        /// Gets DeploymentsServiceApi.
        /// </summary>
        public DeploymentsServiceApi DeploymentsServiceApi => this.deploymentsService.Value;

        /// <summary>
        /// Gets FindingsServiceApi.
        /// </summary>
        public FindingsServiceApi FindingsServiceApi => this.findingsService.Value;

        /// <summary>
        /// Gets MiscServiceApi.
        /// </summary>
        public MiscServiceApi MiscServiceApi => this.miscService.Value;

        /// <summary>
        /// Gets PoliciesServiceApi.
        /// </summary>
        public PoliciesServiceApi PoliciesServiceApi => this.policiesService.Value;

        /// <summary>
        /// Gets ProjectsServiceApi.
        /// </summary>
        public ProjectsServiceApi ProjectsServiceApi => this.projectsService.Value;

        /// <summary>
        /// Gets ScansServiceApi.
        /// </summary>
        public ScansServiceApi ScansServiceApi => this.scansService.Value;

        /// <summary>
        /// Gets SecretsServiceApi.
        /// </summary>
        public SecretsServiceApi SecretsServiceApi => this.secretsService.Value;

        /// <summary>
        /// Gets SupplyChainServiceApi.
        /// </summary>
        public SupplyChainServiceApi SupplyChainServiceApi => this.supplyChainService.Value;

        /// <summary>
        /// Gets TicketingServiceApi.
        /// </summary>
        public TicketingServiceApi TicketingServiceApi => this.ticketingService.Value;

        /// <summary>
        /// Gets TriageServiceApi.
        /// </summary>
        public TriageServiceApi TriageServiceApi => this.triageService.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with SemgrepAdminJwt.
        /// </summary>
        public ISemgrepAdminJwtCredentials SemgrepAdminJwtCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with SemgrepAdminJwt.
        /// </summary>
        public SemgrepAdminJwtModel SemgrepAdminJwtModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken => this.SemgrepAdminJwtCredentials.AccessToken;

        /// <summary>
        /// Gets the credentials to use with SemgrepJwt.
        /// </summary>
        public ISemgrepJwtCredentials SemgrepJwtCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with SemgrepJwt.
        /// </summary>
        public SemgrepJwtModel SemgrepJwtModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken2 => this.SemgrepJwtCredentials.AccessToken;

        /// <summary>
        /// Gets the credentials to use with SemgrepWebToken.
        /// </summary>
        public ISemgrepWebTokenCredentials SemgrepWebTokenCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with SemgrepWebToken.
        /// </summary>
        public SemgrepWebTokenModel SemgrepWebTokenModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken3 => this.SemgrepWebTokenCredentials.AccessToken;

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:SEMGREP.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Semgrep)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the SemgrepWebAppClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (SemgrepAdminJwtModel != null)
            {
                builder.SemgrepAdminJwtCredentials(SemgrepAdminJwtModel.ToBuilder().Build());
            }

            if (SemgrepJwtModel != null)
            {
                builder.SemgrepJwtCredentials(SemgrepJwtModel.ToBuilder().Build());
            }

            if (SemgrepWebTokenModel != null)
            {
                builder.SemgrepWebTokenCredentials(SemgrepWebTokenModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> SemgrepWebAppClient.</returns>
        internal static SemgrepWebAppClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("SEMGREP_WEB_APP_STANDARD_ENVIRONMENT");
            string accessToken = System.Environment.GetEnvironmentVariable("SEMGREP_WEB_APP_STANDARD_ACCESS_TOKEN");
            string accessToken2 = System.Environment.GetEnvironmentVariable("SEMGREP_WEB_APP_STANDARD_ACCESS_TOKEN_2");
            string accessToken3 = System.Environment.GetEnvironmentVariable("SEMGREP_WEB_APP_STANDARD_ACCESS_TOKEN_3");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (accessToken != null)
            {
                builder.SemgrepAdminJwtCredentials(new SemgrepAdminJwtModel
                .Builder(accessToken)
                .Build());
            }

            if (accessToken2 != null)
            {
                builder.SemgrepJwtCredentials(new SemgrepJwtModel
                .Builder(accessToken2)
                .Build());
            }

            if (accessToken3 != null)
            {
                builder.SemgrepWebTokenCredentials(new SemgrepWebTokenModel
                .Builder(accessToken3)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> SemgrepWebAppClient.</returns>
        public static SemgrepWebAppClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = SemgrepWebApp.Standard.Environment.Production;
            private SemgrepAdminJwtModel _semgrepAdminJwtModel = new SemgrepAdminJwtModel();
            private SemgrepJwtModel _semgrepJwtModel = new SemgrepJwtModel();
            private SemgrepWebTokenModel _semgrepWebTokenModel = new SemgrepWebTokenModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for SemgrepAdminJwt.
            /// </summary>
            /// <param name="semgrepAdminJwtModel">SemgrepAdminJwtModel.</param>
            /// <returns>Builder.</returns>
            public Builder SemgrepAdminJwtCredentials(SemgrepAdminJwtModel semgrepAdminJwtModel)
            {
                _semgrepAdminJwtModel = semgrepAdminJwtModel ??
                    throw new ArgumentNullException(nameof(semgrepAdminJwtModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for SemgrepJwt.
            /// </summary>
            /// <param name="semgrepJwtModel">SemgrepJwtModel.</param>
            /// <returns>Builder.</returns>
            public Builder SemgrepJwtCredentials(SemgrepJwtModel semgrepJwtModel)
            {
                _semgrepJwtModel = semgrepJwtModel ??
                    throw new ArgumentNullException(nameof(semgrepJwtModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for SemgrepWebToken.
            /// </summary>
            /// <param name="semgrepWebTokenModel">SemgrepWebTokenModel.</param>
            /// <returns>Builder.</returns>
            public Builder SemgrepWebTokenCredentials(SemgrepWebTokenModel semgrepWebTokenModel)
            {
                _semgrepWebTokenModel = semgrepWebTokenModel ??
                    throw new ArgumentNullException(nameof(semgrepWebTokenModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the SemgrepWebAppClient using the values provided for the builder.
            /// </summary>
            /// <returns>SemgrepWebAppClient.</returns>
            public SemgrepWebAppClient Build()
            {
                if (_semgrepAdminJwtModel.AccessToken == null)
                {
                    _semgrepAdminJwtModel = null;
                }
                if (_semgrepJwtModel.AccessToken == null)
                {
                    _semgrepJwtModel = null;
                }
                if (_semgrepWebTokenModel.AccessToken == null)
                {
                    _semgrepWebTokenModel = null;
                }
                return new SemgrepWebAppClient(
                    _environment,
                    _semgrepAdminJwtModel,
                    _semgrepJwtModel,
                    _semgrepWebTokenModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<SemgrepWebAppClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.SemgrepAdminJwtCredentials != null)
                    builder.SemgrepAdminJwtCredentials(SemgrepAdminJwtModel.FromOptions(options.SemgrepAdminJwtCredentials));
                if (options.SemgrepJwtCredentials != null)
                    builder.SemgrepJwtCredentials(SemgrepJwtModel.FromOptions(options.SemgrepJwtCredentials));
                if (options.SemgrepWebTokenCredentials != null)
                    builder.SemgrepWebTokenCredentials(SemgrepWebTokenModel.FromOptions(options.SemgrepWebTokenCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class SemgrepWebAppClientOptions
        {
            public Environment? Environment { get; set; }
            public SemgrepAdminJwtModelOptions SemgrepAdminJwtCredentials { get; set; }
            public SemgrepJwtModelOptions SemgrepJwtCredentials { get; set; }
            public SemgrepWebTokenModelOptions SemgrepWebTokenCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
